import type { IaPageContent } from './ia-content-types'

const SOURCE_POLICY = {
  label: 'Lextures primary sources policy', href: 'https://github.com/StudyDrift/lextures/blob/main/www/docs/sources-policy.md',
  note: 'Documentation and editorial content distinguish product guidance from research claims and link original sources where available.',
}

export const RESOURCE_CONTENT: Record<string, IaPageContent> = {
  '/resources': {
    eyebrow: 'Learning resources', title: 'Use the right kind of resource for the question',
    lead: 'Move from a quick definition to a practical guide, an evidence review, a reusable planning tool, or product documentation without mistaking one format for another.',
    primaryHref: '/guides', primaryLabel: 'Browse guides', secondaryHref: '/glossary', secondaryLabel: 'Open the glossary',
    answerTitle: 'What is in the Lextures resource library?',
    answer: 'The resource library organizes learning-design and education-technology material by purpose. Guides explain a decision or workflow, the glossary defines essential terms, research pages examine evidence and methods, templates turn ideas into usable plans, the blog develops arguments, and product documentation explains how to complete tasks in Lextures.',
    cardTitle: 'Choose a starting point', cardLead: 'Each collection has a different promise. Start with what you need to understand or accomplish.',
    cards: [
      { title: 'Guides', body: 'Use answer-first explanations and practical sequences for assessment, adaptive learning, grading, standards, LMS operations, and homeschool teaching.', href: '/guides', linkLabel: 'Browse guides' },
      { title: 'Glossary', body: 'Get plain-language definitions, distinctions, examples, and related concepts for terms used across learning systems.', href: '/glossary', linkLabel: 'Look up a term' },
      { title: 'Research', body: 'Review the evidence questions behind Lextures features, our interpretation principles, and links to original publications.', href: '/research', linkLabel: 'Review the research approach' },
      { title: 'Templates', body: 'Start from ready-to-adapt structures for assessment planning, rubric review, course mapping, and LMS evaluation.', href: '/templates', linkLabel: 'Use a template' },
      { title: 'Blog', body: 'Read developed arguments about adaptive learning, assessment validity, rubrics, Bloom’s taxonomy, and AI in education.', href: '/blog', linkLabel: 'Read the blog' },
      { title: 'Product documentation', body: 'Follow task-level instructions for accounts, courses, assessment, grading, integrations, administration, and self-hosting.', href: '/docs', linkLabel: 'Open the help center' },
    ],
    workflowTitle: 'From question to action', workflowLead: 'A reliable learning resource makes the type of claim, supporting evidence, and intended use easy to recognize.',
    steps: [
      { title: '1. Clarify the question', body: 'Decide whether you need a definition, a design decision, implementation steps, a research finding, or a product procedure.' },
      { title: '2. Check the evidence', body: 'Follow citations for numeric, legal, standards, and research claims; note publication date, population, method, and limits.' },
      { title: '3. Adapt and evaluate', body: 'Use the guidance in your context, document the decision, and inspect learner work or operational outcomes before scaling it.' },
    ],
    questionsTitle: 'How we aim to earn trust', questions: ['Answer the main question before expanding the explanation.', 'Link primary evidence for research, numeric, legal, and standards claims.', 'Separate Lextures product behavior from general educational guidance.', 'State meaningful limits instead of turning every topic into a product pitch.'],
    faq: [
      { question: 'What is the difference between guides and documentation?', answer: 'Guides help readers understand or make a broader learning-design decision. Documentation explains how to complete a specific task in the Lextures product. A guide may link to documentation when the reader is ready to implement.' },
      { question: 'Are all resources peer reviewed?', answer: 'No. Research citations may point to peer-reviewed work, but Lextures guides, glossary entries, templates, and blog posts are editorial content. Each format should identify its author, update date, and sources so readers can judge it appropriately.' },
      { question: 'Can I reuse a template?', answer: 'Yes. The templates are designed to be copied and adapted. Keep the decision prompts, replace the examples, and review the result against your learning goals, local policy, and learner needs.' },
    ],
    sources: [SOURCE_POLICY], ctaTitle: 'Begin with a real teaching or platform question', ctaBody: 'Choose a guide for a decision, documentation for a task, or a template when you are ready to make something.',
  },
  '/guides': {
    eyebrow: 'Resources · Guides', title: 'Practical guides for consequential learning decisions',
    lead: 'Understand the evidence, tradeoffs, and implementation questions behind adaptive learning, assessment, grading, standards, LMS operations, and homeschool teaching.',
    primaryHref: '/resources/guides', primaryLabel: 'Explore guide topics', secondaryHref: '/blog', secondaryLabel: 'Read published articles',
    answerTitle: 'What makes a Lextures guide useful?',
    answer: 'A Lextures guide starts with a concrete question, gives a self-contained answer, explains the decision in practical sections, links primary evidence for research or standards claims, and closes with next steps and frequently asked questions. Product links are included only where they help readers apply the guidance.',
    cardTitle: 'Six guide areas', cardLead: 'These clusters reflect recurring decisions educators and platform teams need to make, not a list of search keywords.',
    cards: [
      { title: 'Adaptive learning', body: 'How adaptive systems work, what evidence they need, and when fixed or teacher-led approaches remain a better fit.', href: '/resources/guides#p1', linkLabel: 'Explore adaptive learning' },
      { title: 'Assessment design and AI', body: 'How to preserve validity, clarify allowed assistance, and collect visible evidence of reasoning and transfer.', href: '/resources/guides#p2', linkLabel: 'Explore assessment design' },
      { title: 'Grading and integrity', body: 'Rubrics, feedback, moderation, authorship evidence, and fair responses to suspected academic-integrity problems.', href: '/resources/guides#p3', linkLabel: 'Explore grading' },
      { title: 'Mastery and standards', body: 'Outcome mapping, evidence rules, reassessment, and reporting that communicates more than a single average.', href: '/resources/guides#p4', linkLabel: 'Explore mastery' },
      { title: 'Choosing and running an LMS', body: 'Requirements, interoperability, accessibility, governance, migration, implementation, and total operating effort.', href: '/resources/guides#p5', linkLabel: 'Explore LMS operations' },
      { title: 'Homeschool teaching', body: 'Curriculum planning, pacing, feedback, records, and using evidence without recreating an institutional classroom at home.', href: '/resources/guides#p6', linkLabel: 'Explore homeschool teaching' },
    ],
    workflowTitle: 'How to use a guide', workflowLead: 'A guide should improve a decision, not merely add reading to the decision process.',
    steps: [
      { title: '1. Read the answer and limits', body: 'Start with the direct answer, key takeaways, audience, and qualifications to decide whether the guide fits your context.' },
      { title: '2. Follow the evidence', body: 'Open the original research, standard, statute, or vendor documentation behind any claim that matters to your decision.' },
      { title: '3. Apply a small version', body: 'Use the checklist or linked template, test the practice with a manageable group, and define what evidence would justify a change.' },
    ],
    questionsTitle: 'Evaluate a guide by asking', questions: ['Does it answer a real question in plain language?', 'Are evidence claims linked to the source that actually supports them?', 'Does it distinguish findings from interpretation and product behavior?', 'Are the limits and implementation tradeoffs clear?'],
    faq: [
      { question: 'Why do some guide topics have more articles than others?', answer: 'The editorial library grows by reviewed topic clusters. A cluster becomes a full guide when it has enough distinct, useful coverage; article counts indicate current depth rather than a claim that every topic is complete.' },
      { question: 'How current are the guides?', answer: 'Published content carries publication and update dates. Time-sensitive claims and citations belong in the editorial refresh process, while product procedures are maintained in the help center.' },
      { question: 'Where should I go for step-by-step product help?', answer: 'Use the Lextures documentation for product procedures. Guides may explain why to choose a workflow; docs show where controls are and how to complete it.' },
    ],
    sources: [SOURCE_POLICY], ctaTitle: 'Choose the decision you need to make', ctaBody: 'Open a guide cluster, then move to documentation or a template when you are ready to apply it.',
  },
  '/glossary': {
    eyebrow: 'Resources · Glossary', title: 'Learning and LMS terms, explained for decisions',
    lead: 'Use concise definitions, practical distinctions, and examples to understand the language of assessment, adaptive learning, grading, accessibility, AI, and interoperability.',
    primaryHref: '#terms', primaryLabel: 'Browse the terms', secondaryHref: '/guides', secondaryLabel: 'Read the guides',
    answerTitle: 'What does this glossary cover?',
    answer: 'The Lextures glossary defines terms that educators, learners, administrators, and technology teams encounter when designing or operating a learning environment. Entries emphasize what a term means, what it does not mean, and why the distinction matters. Standards-based definitions link to the organization responsible for the standard.',
    cardTitle: 'Use a definition in context', cardLead: 'A label becomes meaningful when it changes how you design a task, interpret evidence, or specify a system requirement.',
    cards: [
      { title: 'Learning and practice', body: 'Adaptive learning, retrieval practice, spaced repetition, mastery, misconception, and Item Response Theory.' },
      { title: 'Assessment and grading', body: 'Formative and summative assessment, validity, reliability, rubric, criterion, outcome, moderation, and grade posting.' },
      { title: 'Access and design', body: 'Accessibility, accommodation, Universal Design for Learning, alternative text, captions, and assistive technology.' },
      { title: 'Systems and data', body: 'LMS, LTI, QTI, OneRoster, SSO, SCIM, API, MCP, interoperability, and source of truth.' },
    ],
    workflowTitle: 'How to read a glossary entry', workflowLead: 'Definitions are a starting point. Follow the related guide or primary standard before making a high-stakes policy or procurement decision.',
    steps: [
      { title: '1. Read the plain-language meaning', body: 'Identify the central idea without assuming the term is a product feature, guarantee, or complete teaching method.' },
      { title: '2. Check the distinction', body: 'Compare adjacent terms—such as formative versus summative, accommodation versus modification, or score versus mastery.' },
      { title: '3. Apply it to a decision', body: 'Use the definition to improve an assessment plan, report interpretation, integration requirement, or conversation with a learner.' },
    ],
    faq: [
      { question: 'Are glossary definitions specific to Lextures?', answer: 'Most entries explain the broader education or technology term. When Lextures implements the idea in a particular way, the entry or related platform page should identify that product-specific behavior separately.' },
      { question: 'Which source controls a standards term?', answer: 'The organization that publishes the standard is authoritative for its definition and requirements—for example W3C for WCAG and 1EdTech for LTI, QTI, and OneRoster.' },
      { question: 'How can I suggest a missing term?', answer: 'Use the project’s public repository or contact channel with the term, the context where you encountered it, and the decision the definition should help a reader make.' },
    ],
    sources: [
      { label: 'W3C WCAG 2.2 glossary', href: 'https://www.w3.org/TR/WCAG22/#glossary', note: 'Normative definitions used by the Web Content Accessibility Guidelines.' },
      { label: '1EdTech standards', href: 'https://www.1edtech.org/standards', note: 'Official specifications and overviews for education interoperability standards.' },
    ],
    ctaTitle: 'Turn the term into a better question', ctaBody: 'Use the definition, compare related concepts, then follow a guide or the responsible standard for depth.',
  },
  '/research': {
    eyebrow: 'Resources · Research', title: 'The evidence questions behind an adaptive learning platform',
    lead: 'See what Lextures needs to learn, how product signals should be interpreted, and which original research and standards inform the work.',
    primaryHref: '/blog', primaryLabel: 'Read current analyses', secondaryHref: '/platform/analytics', secondaryLabel: 'Explore analytics',
    answerTitle: 'What does Lextures mean by research?',
    answer: 'Lextures research connects published evidence, transparent product questions, and analysis of platform behavior. This page does not present marketing metrics as research or imply that a feature causes learning gains by itself. Strong claims require a stated method, population, comparison, uncertainty, limitations, and access to the supporting source or report.',
    cardTitle: 'Research questions worth answering', cardLead: 'The program is organized around decisions that affect learners and educators, including where a system should remain uncertain.',
    cards: [
      { title: 'Adaptive routing and calibration', body: 'When does item routing produce useful practice, how much item evidence is sufficient, and where do sparse or biased banks distort estimates?' },
      { title: 'Feedback and revision', body: 'Which feedback timing and forms help learners make a better next attempt, and how does the effect vary by task and prior knowledge?' },
      { title: 'Assessment validity with AI', body: 'Which task designs preserve evidence of learner reasoning when generative tools are available, and what process evidence is proportionate?' },
      { title: 'Access and differential outcomes', body: 'Where do interfaces, content formats, accommodations, or models create different error rates or barriers across learner groups?' },
      { title: 'Instructor decision support', body: 'Do misconception and mastery signals lead to accurate, timely instructional actions rather than alert fatigue or over-intervention?' },
      { title: 'Interoperable learning records', body: 'Can outcomes and activity retain meaning as they move among course, roster, assessment, and reporting systems?' },
    ],
    workflowTitle: 'A minimum standard for a Lextures study', workflowLead: 'Research quality comes from a clear question and an inspectable method, not a large dashboard number.',
    steps: [
      { title: '1. State the question and protocol', body: 'Define the population, intervention or exposure, comparison, outcomes, exclusions, analysis, and privacy protections before interpreting results.' },
      { title: '2. Analyze with context', body: 'Report missingness, uncertainty, subgroup considerations, implementation differences, and alternative explanations alongside the result.' },
      { title: '3. Publish limits and implications', body: 'Separate observation from causal inference, make conflicts visible, link materials where appropriate, and say what should—and should not—change.' },
    ],
    questionsTitle: 'How to evaluate a learning claim', questions: ['Was the outcome actual learning, a proxy such as completion, or a satisfaction measure?', 'Does the method support a causal claim or only an association?', 'Who was included, excluded, or missing from the analysis?', 'Is the effect educationally meaningful and reproducible in the intended context?'],
    faq: [
      { question: 'Does Lextures currently claim that its features improve learning outcomes?', answer: 'This page makes no blanket causal claim. A feature can be informed by learning science without proving that every implementation improves outcomes. Any future efficacy claim should link a study with the necessary design, measures, and limitations.' },
      { question: 'Are blog posts research publications?', answer: 'No. Blog posts are editorial analyses. They can interpret and cite research, but they are not peer-reviewed studies unless explicitly linked to a separately published research report.' },
      { question: 'Why publish negative or inconclusive findings?', answer: 'They help prevent ineffective changes, reveal where measures or implementations need improvement, and reduce selective reporting. They are necessary for trustworthy product learning.' },
    ],
    sources: [
      { label: 'U.S. Department of Education What Works Clearinghouse standards', href: 'https://ies.ed.gov/ncee/wwc/Handbooks', note: 'Study-design and evidence standards for evaluating education interventions.' },
      { label: 'NIST AI Risk Management Framework', href: 'https://doi.org/10.6028/NIST.AI.100-1', note: 'Guidance for governing, mapping, measuring, and managing AI risk.' },
    ],
    ctaTitle: 'Read claims with the method attached', ctaBody: 'Explore current analyses, then follow their citations to the original evidence and its limitations.',
  },
  '/templates': {
    eyebrow: 'Resources · Templates', title: 'Reusable structures for better learning decisions',
    lead: 'Start with the questions that are easy to miss: the evidence you need, the barrier you might introduce, the person responsible, and the signal that would make you revise the plan.',
    primaryHref: '#template-library', primaryLabel: 'Browse templates', secondaryHref: '/guides', secondaryLabel: 'Read the guides',
    answerTitle: 'How should educators use these templates?',
    answer: 'Copy a template, replace its prompts with local context, and remove sections that do not serve the decision. A template is a thinking scaffold, not proof of quality or compliance. Review the completed version with the learners, educators, accessibility specialists, or technology owners affected by the plan before putting it into practice.',
    cardTitle: 'Template library', cardLead: 'Each compact structure can be copied into a document, ticket, planning board, or course-development workflow.',
    cards: [
      { title: 'Assessment evidence plan', body: 'Objective · evidence learners will produce · allowed resources and AI use · success criteria · access needs · feedback timing · follow-up action.' },
      { title: 'Rubric quality review', body: 'Criterion · observable evidence · performance distinctions · weighting · examples · potential bias or ambiguity · learner-facing revision.' },
      { title: 'Course map', body: 'Outcome · module · learning activity · practice · assessment · feedback · prerequisite · estimated workload · accessibility check.' },
      { title: 'Learning analytics action plan', body: 'Decision · signal · source evidence · threshold or pattern · possible alternative explanations · response · owner · review date.' },
      { title: 'LMS evaluation scorecard', body: 'Required workflow · user group · scenario · evidence from demo or pilot · accessibility · interoperability · data ownership · operating effort · decision.' },
      { title: 'AI use-case review', body: 'Purpose · affected people · data sent · provider · likely failures · human reviewer · disclosure · recourse · non-AI fallback · monitoring.' },
    ],
    workflowTitle: 'Make a template earn its place', workflowLead: 'The value is in the conversation and evidence the prompts produce, not in completing every field.',
    steps: [
      { title: '1. Copy and narrow', body: 'Name one decision, audience, course, or workflow. Delete prompts that do not apply and add local policy or learner needs.' },
      { title: '2. Complete it with evidence', body: 'Link objectives, example work, standards, user research, integration documentation, or policy instead of filling fields with general assurances.' },
      { title: '3. Review after use', body: 'Set a date and owner, inspect what happened, and record which assumption, criterion, or workflow should change next time.' },
    ],
    questionsTitle: 'A useful completed template is', questions: ['Specific enough that another person can understand the decision.', 'Short enough to be reviewed before the work begins.', 'Linked to the evidence or policy behind important constraints.', 'Owned by a person and paired with a review point.'],
    faq: [
      { question: 'Can I edit and share these templates?', answer: 'Yes. These structures are intended to be copied, shortened, and adapted. Preserve links to relevant evidence and local policy, and remove Lextures-specific examples when they do not fit your setting.' },
      { question: 'Do the templates guarantee accessibility or compliance?', answer: 'No. They prompt important questions but cannot replace review by qualified people, testing with affected users, or analysis of the laws and policies that apply to your organization.' },
      { question: 'Where can I learn how to fill one out?', answer: 'Use the related Lextures guides for decision context and the product documentation for implementation steps. Begin with the template’s objective or decision field, then add only evidence that helps resolve it.' },
    ],
    sources: [SOURCE_POLICY], ctaTitle: 'Copy one structure and use it on a real decision', ctaBody: 'Keep the scope small, attach evidence, name the owner, and schedule the review before the plan disappears into a folder.',
  },
}

export type GlossaryTerm = { term: string; definition: string; related: string }

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { term: 'Accommodation', definition: 'A change in access, timing, setting, presentation, or response that reduces a barrier without changing the learning construct being measured.', related: 'Accessibility · modification · Universal Design for Learning' },
  { term: 'Adaptive learning', definition: 'A learning experience that changes content, sequence, difficulty, support, or timing from evidence about the learner or context.', related: 'Item Response Theory · mastery · spaced repetition' },
  { term: 'API', definition: 'An application programming interface: a documented way for software systems to request actions or exchange data.', related: 'Integration · MCP · interoperability' },
  { term: 'Assessment validity', definition: 'The degree to which evidence and theory support the interpretation and use of assessment results for a stated purpose.', related: 'Reliability · construct · formative assessment' },
  { term: 'Formative assessment', definition: 'A process that elicits and interprets evidence during learning so learners and educators can decide what to do next.', related: 'Feedback · summative assessment · misconception' },
  { term: 'Interoperability', definition: 'The ability of systems to exchange data or services and use what was exchanged with its intended meaning intact.', related: 'LTI · QTI · OneRoster · API' },
  { term: 'Item Response Theory (IRT)', definition: 'A family of psychometric models relating the probability of an item response to learner ability and item characteristics such as difficulty and discrimination.', related: 'Adaptive testing · item bank · ability estimate' },
  { term: 'Learning management system (LMS)', definition: 'Software for organizing, delivering, administering, tracking, and supporting courses and learning activity.', related: 'Course · integration · virtual learning environment' },
  { term: 'Learning Tools Interoperability (LTI)', definition: 'A 1EdTech standard for securely launching learning tools from platforms and exchanging supported context and service data.', related: 'Integration · single sign-on · grade return' },
  { term: 'Mastery', definition: 'A judgment that available evidence meets a defined level of competence for a skill, standard, or outcome; it is not synonymous with completion.', related: 'Outcome · standards-based grading · proficiency' },
  { term: 'Misconception', definition: 'A systematic but inaccurate idea or reasoning pattern, often inferred from explanations or repeated response patterns rather than one wrong answer.', related: 'Distractor · item analysis · feedback' },
  { term: 'Model Context Protocol (MCP)', definition: 'An open protocol for connecting AI applications to tools and contextual data through defined server capabilities.', related: 'AI agent · API · access scope' },
  { term: 'OneRoster', definition: 'A 1EdTech standard for exchanging K–12 roster, course, enrollment, resource, and gradebook data through CSV or REST services.', related: 'SIS · roster sync · interoperability' },
  { term: 'Outcome', definition: 'A statement of what a learner should know, understand, or be able to do, used to align learning activity and evidence.', related: 'Objective · standard · mastery' },
  { term: 'Question and Test Interoperability (QTI)', definition: 'A 1EdTech specification for representing and exchanging assessment items, tests, and related results.', related: 'Question bank · assessment · import' },
  { term: 'Reliability', definition: 'The consistency or precision of scores or decisions across relevant occasions, tasks, items, or raters.', related: 'Validity · moderation · measurement error' },
  { term: 'Retrieval practice', definition: 'Practice that requires recalling information or skills from memory rather than only reviewing the material again.', related: 'Spaced repetition · practice · feedback' },
  { term: 'Rubric', definition: 'A set of criteria and performance descriptions used to evaluate work and communicate what quality looks like.', related: 'Criterion · feedback · moderation' },
  { term: 'SCIM', definition: 'System for Cross-domain Identity Management, an HTTP-based standard for provisioning and managing user identity data across systems.', related: 'SSO · identity provider · deprovisioning' },
  { term: 'Single sign-on (SSO)', definition: 'An authentication arrangement that lets a user access connected systems through an established identity-provider session.', related: 'SAML · OIDC · identity provider' },
  { term: 'Spaced repetition', definition: 'A practice schedule that revisits material across separated intervals, often adjusting the next interval from prior performance.', related: 'Retrieval practice · adaptive learning · review queue' },
  { term: 'Summative assessment', definition: 'Assessment used primarily to summarize achievement at a point in time for a grade, credential, placement, or other decision.', related: 'Formative assessment · validity · grading' },
  { term: 'Universal Design for Learning (UDL)', definition: 'A CAST framework for reducing barriers through multiple means of engagement, representation, and action and expression.', related: 'Accessibility · accommodation · learner agency' },
  { term: 'WCAG', definition: 'The W3C Web Content Accessibility Guidelines, a testable technical standard for making web content more accessible to people with disabilities.', related: 'Accessibility · conformance · assistive technology' },
]
