package platformconfig

import "github.com/lextures/lextures/server/internal/config"

func applyPlatformBools(out *config.Config, db *Row, def Defaults) {
	// Feature flags are DB-managed (no env seed); a missing settings row means "all columns
	// unset", so every flag falls back to its documented default below.
	if db == nil {
		db = &Row{}
	}
	out.SAMLSSOEnabled = mergeBool(db.SAMLSSOEnabled, false)
	out.AnnotationEnabled = mergeBool(db.AnnotationEnabled, false)
	out.FeedbackMediaEnabled = mergeBool(db.FeedbackMediaEnabled, false)
	out.BlindGradingEnabled = mergeBool(db.BlindGradingEnabled, def.BlindGradingEnabled)
	out.ModeratedGradingEnabled = mergeBool(db.ModeratedGradingEnabled, false)
	out.OriginalityDetectionEnabled = mergeBool(db.OriginalityDetectionEnabled, false)
	out.OriginalityStubExternal = mergeBool(db.OriginalityStubExternal, false)
	out.GradePostingPoliciesEnabled = mergeBool(db.GradePostingPoliciesEnabled, def.GradePostingPoliciesEnabled)
	out.GradebookCSVEnabled = mergeBool(db.GradebookCSVEnabled, false)
	out.ResubmissionWorkflowEnabled = mergeBool(db.ResubmissionWorkflowEnabled, false)
	out.LTIEnabled = mergeBool(db.LTIEnabled, false)
	out.OneRosterEnabled = mergeBool(db.OneRosterEnabled, false)
	out.ScimEnabled = mergeBool(db.ScimEnabled, false)
	out.OIDCSSOEnabled = mergeBool(db.OIDCSSOEnabled, false)
	out.CleverSSOEnabled = mergeBool(db.CleverSSOEnabled, false)
	out.ClassLinkSSOEnabled = mergeBool(db.ClassLinkSSOEnabled, false)
	out.MFAEnabled = mergeBool(db.MFAEnabled, false)
	out.MagicLinkEnabled = mergeBool(db.MagicLinkEnabled, def.MagicLinkEnabled)
	out.MagicLinkEnrolledOnly = mergeBool(db.MagicLinkEnrolledOnly, false)
	out.SessionManagementUIEnabled = mergeBool(db.SessionManagementUIEnabled, false)
	out.EmailNotificationsEnabled = mergeBool(db.EmailNotificationsEnabled, false)
	// SES email provider is opt-in (default off).
	out.FFEmailSES = mergeBool(db.FFEmailSES, false)
	out.PushNotificationsEnabled = mergeBool(db.PushNotificationsEnabled, false)
	out.VirtualClassroomEnabled = mergeBool(db.VirtualClassroomEnabled, def.VirtualClassroomEnabled)
	out.DRMEnabled = mergeBool(db.DRMEnabled, false)
	out.VideoTranscodingEnabled = mergeBool(db.VideoTranscodingEnabled, false)
	out.AutoCaptioningEnabled = mergeBool(db.AutoCaptioningEnabled, false)
	out.VideoCaptionsEnabled = mergeBool(db.VideoCaptionsEnabled, false)
	out.StorageQuotasEnabled = mergeBool(db.StorageQuotasEnabled, false)
	out.AtRiskAlertsEnabled = mergeBool(db.AtRiskAlertsEnabled, false)
	out.AvScanningEnabled = mergeBool(db.AvScanningEnabled, false)
	out.ClamAVStub = mergeBool(db.ClamAVStub, false)
	out.H5PEnabled = mergeBool(db.H5PEnabled, false)
	out.ScormIngestionEnabled = mergeBool(db.ScormIngestionEnabled, false)
	out.OERLibraryEnabled = mergeBool(db.OERLibraryEnabled, false)
	out.OERStub = mergeBool(db.OERStub, false)
	out.ItemAnalysisEnabled = mergeBool(db.ItemAnalysisEnabled, false)
	out.StudentProgressEnabled = mergeBool(db.StudentProgressEnabled, true)
	out.EngagementTrackingEnabled = mergeBool(db.EngagementTrackingEnabled, false)
	out.SelfReflectionEnabled = mergeBool(db.SelfReflectionEnabled, false)
	out.LearnerProfileEnabled = mergeBool(db.LearnerProfileEnabled, true)
	out.LpAdaptRecommendationsEnabled = mergeBool(db.LpAdaptRecommendationsEnabled, false)
	out.LpAdaptReviewEnabled = mergeBool(db.LpAdaptReviewEnabled, false)
	out.LpAdaptModalityEnabled = mergeBool(db.LpAdaptModalityEnabled, false)
	out.LpAdaptTutorEnabled = mergeBool(db.LpAdaptTutorEnabled, false)
	out.IntroCourseEnabled = mergeBool(db.IntroCourseEnabled, true)
	out.OutcomesReportEnabled = mergeBool(db.OutcomesReportEnabled, false)
	out.InstructorInsightsEnabled = mergeBool(db.InstructorInsightsEnabled, false)
	out.EquationEditorEnabled = mergeBool(db.EquationEditorEnabled, false)
	out.ReadingLevelEnabled = mergeBool(db.ReadingLevelEnabled, false)
	out.GraderAgentEnabled = mergeBool(db.GraderAgentEnabled, false)
	out.GraderAgentReviewInboxEnabled = mergeBool(db.GraderAgentReviewInboxEnabled, false)
	out.GraderAgentSuggestModeEnabled = mergeBool(db.GraderAgentSuggestModeEnabled, false)
	out.GraderAgentTextEntryGradingEnabled = mergeBool(db.GraderAgentTextEntryGradingEnabled, true)
	out.GraderAgentVisionGradingEnabled = mergeBool(db.GraderAgentVisionGradingEnabled, false)
	out.GraderAgentRunFiltersEnabled = mergeBool(db.GraderAgentRunFiltersEnabled, false)
	out.GraderAgentCostEstimateEnabled = mergeBool(db.GraderAgentCostEstimateEnabled, false)
	out.GraderAgentCancelRunEnabled = mergeBool(db.GraderAgentCancelRunEnabled, false)
	out.CodeExecutionEnabled = mergeBool(db.CodeExecutionEnabled, false)
	out.AltTextEnforcementEnabled = mergeBool(db.AltTextEnforcementEnabled, false)
	out.FFAltTextEnforcement = mergeBool(db.FFAltTextEnforcement, false)
	out.FFHighContrastReducedMotion = mergeBool(db.FFHighContrastReducedMotion, false)
	// AN.2 navigation transitions default ON; kill-switch via Settings → Global platform.
	out.FFMotionNavigation = mergeBool(db.FFMotionNavigation, true)
	// AN.3 load choreography default ON; kill-switch via Settings → Global platform.
	out.FFMotionReveal = mergeBool(db.FFMotionReveal, true)
	// AN.4 list/collection motion default ON; kill-switch via Settings → Global platform.
	out.FFMotionLists = mergeBool(db.FFMotionLists, true)
	out.FFMobileCreateCourse = mergeBool(db.FFMobileCreateCourse, false)
	out.FFMobileCourseCreateV2 = mergeBool(db.FFMobileCourseCreateV2, false)
	out.FFMobileCanvasImport = mergeBool(db.FFMobileCanvasImport, false)
	out.FFMobileAdminConsole = mergeBool(db.FFMobileAdminConsole, false)
	out.FFParentPortal = mergeBool(db.FFParentPortal, false)
	out.FFParentPortalV2 = mergeBool(db.FFParentPortalV2, false)
	out.FFReportCards = mergeBool(db.FFReportCards, false)
	out.FFSISIntegration = mergeBool(db.FFSISIntegration, false)
	out.FFCatalogIntegration = mergeBool(db.FFCatalogIntegration, false)
	out.FFEnrollmentStateMachine = mergeBool(db.FFEnrollmentStateMachine, false)
	out.FFIncompleteGradeWorkflow = mergeBool(db.FFIncompleteGradeWorkflow, false)
	out.FFLibrary = mergeBool(db.FFLibrary, false)
	out.FFBroadcasts = mergeBool(db.FFBroadcasts, false)
	out.FFConferenceScheduling = mergeBool(db.FFConferenceScheduling, false)
	out.FFDemographics = mergeBool(db.FFDemographics, false)
	out.FFContentFilterIntegration = mergeBool(db.FFContentFilterIntegration, false)
	out.FFUiMode = mergeBool(db.FFUiMode, false)
	out.FFGradeSubmission = mergeBool(db.FFGradeSubmission, false)
	out.FFWhatifGrades = mergeBool(db.FFWhatifGrades, false)
	out.FFGradeCurving = mergeBool(db.FFGradeCurving, false)
	out.FFAcademicCalendar = mergeBool(db.FFAcademicCalendar, false)
	out.FFPlagiarismChecks = mergeBool(db.FFPlagiarismChecks, false)
	out.FFCourseEvaluations = mergeBool(db.FFCourseEvaluations, false)
	out.FFProctoringIntegration = mergeBool(db.FFProctoringIntegration, false)
	out.FFCoCurricularTranscript = mergeBool(db.FFCoCurricularTranscript, false)
	out.FFEportfolio = mergeBool(db.FFEportfolio, false)
	out.FFBookstoreIntegration = mergeBool(db.FFBookstoreIntegration, false)
	out.FFTranscripts = mergeBool(db.FFTranscripts, false)
	out.FFTranscriptInbound = mergeBool(db.FFTranscriptInbound, false)
	out.FFDiplomas = mergeBool(db.FFDiplomas, false)
	out.FFWebhooks = mergeBool(db.FFWebhooks, false)
	out.FFZapierConnector = mergeBool(db.FFZapierConnector, false)
	out.FFMarketplace = mergeBool(db.FFMarketplace, false)
	out.FFAdvisingIntegration = mergeBool(db.FFAdvisingIntegration, false)
	out.FFResearchConsent = mergeBool(db.FFResearchConsent, false)
	out.FFAccessibilityIntake = mergeBool(db.FFAccessibilityIntake, false)
	out.FFCEUTracking = mergeBool(db.FFCEUTracking, false)
	out.FFConsortiumSharing = mergeBool(db.FFConsortiumSharing, false)
	out.FFSelfPacedMode = mergeBool(db.FFSelfPacedMode, false)
	out.FFPublicCatalog = mergeBool(db.FFPublicCatalog, false)
	// Course marketplace defaults ON (exception to the usual default-off convention; plan MKT1).
	out.FFCourseMarketplace = mergeBool(db.FFCourseMarketplace, true)
	out.FFFeedback = mergeBool(db.FFFeedback, true)
	// Collaboration boards are course-scoped only; platform master switch removed.
	out.FFVisualBoards = true
	// Boards realtime defaults ON so multi-user boards sync live without a refresh.
	out.FFBoardsRealtime = mergeBool(db.FFBoardsRealtime, true)
	out.FFBoardsExternalSharing = mergeBool(db.FFBoardsExternalSharing, false)
	// Live Quizzes are course-scoped only; platform master switch removed.
	out.FFInteractiveQuizzes = true
	// Live hosting is the core of Live Quizzes; default ON so course enable is enough to host.
	out.FFIqLiveHosting = mergeBool(db.FFIqLiveHosting, true)
	out.FFIqTeamMode = mergeBool(db.FFIqTeamMode, false)
	out.FFIqStudentPaced = mergeBool(db.FFIqStudentPaced, false)
	out.FFIqHomework = mergeBool(db.FFIqHomework, false)
	out.FFIqGradebookPush = mergeBool(db.FFIqGradebookPush, false)
	out.FFIqPublicKitCatalog = mergeBool(db.FFIqPublicKitCatalog, false)
	out.FFIqGuestJoin = mergeBool(db.FFIqGuestJoin, false)
	out.FFIqAiGeneration = mergeBool(db.FFIqAiGeneration, false)
	out.FFPublicAPI = mergeBool(db.FFPublicAPI, false)
	out.FFStripeBilling = mergeBool(db.FFStripeBilling, false)
	out.FFPaymentsEnabled = mergeBool(db.FFPaymentsEnabled, false)
	out.FFRevenueShare = mergeBool(db.FFRevenueShare, false)
	out.FFTaxCollection = mergeBool(db.FFTaxCollection, false)
	out.FFLearningPaths = mergeBool(db.FFLearningPaths, false)
	out.FFConditionalRelease = mergeBool(db.FFConditionalRelease, false)
	out.FFPeerReview = mergeBool(db.FFPeerReview, false)
	out.FFCompletionCredentials = mergeBool(db.FFCompletionCredentials, false)
	out.FFCourseReviews = mergeBool(db.FFCourseReviews, false)
	out.FFGamification = mergeBool(db.FFGamification, false)
	out.FFCompetencyBadges = mergeBool(db.FFCompetencyBadges, false)
	out.BadgesDefaultPublic = mergeBool(db.BadgesDefaultPublic, false)
	out.FFOnboardingFlow = mergeBool(db.FFOnboardingFlow, false)
	out.FFStudyReminders = mergeBool(db.FFStudyReminders, false)
	out.FFAIStudyBuddy = mergeBool(db.FFAIStudyBuddy, false)
	out.FFLessonGenerator = mergeBool(db.FFLessonGenerator, false)
	out.FFPersistentTutor = mergeBool(db.FFPersistentTutor, false)
	out.FFAPITokens = mergeBool(db.FFAPITokens, false)
	out.FFBotSlack = mergeBool(db.FFBotSlack, false)
	out.FFBotTeams = mergeBool(db.FFBotTeams, false)
	out.FFBotDiscord = mergeBool(db.FFBotDiscord, false)
	out.FFCalendarFeeds = mergeBool(db.FFCalendarFeeds, true)
	out.FFRedisCache = mergeBool(db.FFRedisCache, false)
	out.SpeechToTextEnabled = mergeBool(db.SpeechToTextEnabled, false)
	out.AccommodationsEngineEnabled = mergeBool(db.AccommodationsEngineEnabled, false)
	out.FFAccommodationsEngine = mergeBool(db.FFAccommodationsEngine, false)
	out.ReadAloudEnabled = mergeBool(db.ReadAloudEnabled, false)
	out.FFReadAloud = mergeBool(db.FFReadAloud, false)
	out.TranslationMemoryEnabled = mergeBool(db.TranslationMemoryEnabled, false)
	out.ReportExportEnabled = mergeBool(db.ReportExportEnabled, false)
	out.XAPIEmissionEnabled = mergeBool(db.XAPIEmissionEnabled, false)
	out.LRSAnonymizeActors = mergeBool(db.LRSAnonymizeActors, false)
	out.FERPAWorkflowEnabled = mergeBool(db.FERPAWorkflowEnabled, false)
	out.CoppaWorkflowEnabled = mergeBool(db.CoppaWorkflowEnabled, false)
	out.GDPRModuleEnabled = mergeBool(db.GDPRModuleEnabled, false)
	out.CCPAModuleEnabled = mergeBool(db.CCPAModuleEnabled, false)
	out.DPAPortalEnabled = mergeBool(db.DPAPortalEnabled, false)
	out.StatePrivacyEnabled = mergeBool(db.StatePrivacyEnabled, false)
	out.SOC2ModuleEnabled = mergeBool(db.SOC2ModuleEnabled, false)
	out.IsoIsmsEnabled = mergeBool(db.IsoIsmsEnabled, false)
	out.AdminAuditLogEnabled = mergeBool(db.AdminAuditLogEnabled, def.AdminAuditLogEnabled)
	out.AdminConsoleEnabled = mergeBool(db.AdminConsoleEnabled, false)
	out.ImpersonationEnabled = mergeBool(db.ImpersonationEnabled, false)
	out.BulkCsvImportEnabled = mergeBool(db.BulkCsvImportEnabled, false)
	out.AdminSearchEnabled = mergeBool(db.AdminSearchEnabled, false)
	out.EmailTemplateEditorEnabled = mergeBool(db.EmailTemplateEditorEnabled, false)
	out.MaintenanceBannerEnabled = mergeBool(db.MaintenanceBannerEnabled, true)
	out.CustomFieldsEnabled = mergeBool(db.CustomFieldsEnabled, false)
	out.SeatManagementEnabled = mergeBool(db.SeatManagementEnabled, false)
	out.DataResidencyEnabled = mergeBool(db.DataResidencyEnabled, false)
	out.AiDisclosureEnabled = mergeBool(db.AiDisclosureEnabled, def.AiDisclosureEnabled)
	out.RTLEnabled = mergeBool(db.RTLEnabled, false)
	out.SecurityDisclosureModuleEnabled = mergeBool(db.SecurityDisclosureModuleEnabled, false)
	out.BackupModuleEnabled = mergeBool(db.BackupModuleEnabled, false)
	out.FFReadingPreferences = mergeBool(db.FFReadingPreferences, false)
	out.FFClassroomSignals = mergeBool(db.FFClassroomSignals, false)
	out.FFLibraryIntegration = mergeBool(db.FFLibraryIntegration, false)

	// Adaptive-learning platform gates (previously env-only service flags).
	out.DiagnosticAssessmentsEnabled = mergeBool(db.DiagnosticAssessmentsEnabled, false)
	out.SRSPracticeEnabled = mergeBool(db.SRSPracticeEnabled, false)
	out.IRTCatModeEnabled = mergeBool(db.IRTCatModeEnabled, false)
	out.AdaptiveLearnerModelEnabled = mergeBool(db.AdaptiveLearnerModelEnabled, false)
	out.LearnerModelEMAAlpha = mergeFloat64(db.LearnerModelEMAAlpha, def.LearnerModelEMAAlpha)
}
