/** Centralized copy for the public Courses storefront (plans MKT8–MKT10). */

export const COURSES_COPY = {
  navLabel: 'Courses',
  pageTitle: 'Courses — Lextures',
  pageDescription:
    'Browse free and paid courses on Lextures. Learn at your own pace with adaptive quizzes and spaced review.',
  heroEyebrow: 'Courses',
  heroTitle: 'Learn something new today',
  heroLead: 'Browse marketplace courses — free and paid — then enroll on Lextures to start learning.',
  searchLabel: 'Search courses',
  searchPlaceholder: 'Search by title, topic, or instructor',
  categoriesLabel: 'Categories',
  allCategories: 'All',
  levelLabel: 'Level',
  anyLevel: 'Any level',
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
  languageLabel: 'Language',
  anyLanguage: 'Any language',
  priceLabel: 'Price',
  anyPrice: 'Any price',
  freeOnly: 'Free only',
  sortLabel: 'Sort by',
  sortPopular: 'Most popular',
  sortNewest: 'Newest',
  sortPrice: 'Price: low to high',
  sortRating: 'Highest rated',
  free: 'Free',
  loadMore: 'Load more',
  resultsCount: (n: number) => (n === 1 ? '1 course' : `${n} courses`),
  emptyTitle: 'No courses available yet',
  emptyBody: 'Check back soon — new courses are added regularly.',
  unavailableTitle: 'Courses are not available right now',
  unavailableBody: 'The course marketplace is temporarily unavailable. Please try again later.',
  errorTitle: 'Something went wrong',
  errorBody: 'We could not load courses. Check your connection and try again.',
  retry: 'Retry',
  enrollFree: 'Enroll — Free',
  enrollPaid: (price: string) => `Enroll — ${price}`,
  whatsIncluded: "What's included",
  modules: (n: number) => (n === 1 ? '1 module' : `${n} modules`),
  items: (n: number) => (n === 1 ? '1 lesson' : `${n} lessons`),
  duration: (mins: number) => {
    if (mins < 60) return `About ${mins} min`
    const hours = Math.round(mins / 60)
    return hours === 1 ? 'About 1 hour' : `About ${hours} hours`
  },
  reviews: 'Reviews',
  noReviews: 'No reviews yet',
  showMoreReviews: 'Show more',
  notFoundTitle: 'Course not found',
  notFoundBody: 'This course is not listed or may have been removed.',
  backToCourses: 'Back to courses',
  viewOnLextures: 'View on Lextures',
  breadcrumbCourses: 'Courses',
  students: (n: number) => (n === 1 ? '1 student' : `${n.toLocaleString()} students`),
  ratingLabel: (avg: number, count: number) =>
    `${avg.toFixed(1)} out of 5 stars${count > 0 ? `, ${count} ratings` : ''}`,
} as const
