export type Integration = { slug: string; name: string; version: string; capability: string; effort: string; helpPath: string; native: boolean }

export const INTEGRATIONS: Integration[] = [
  { slug: 'lti-1-3', name: 'LTI 1.3 and LTI Advantage', version: 'LTI 1.3; deployment-dependent Advantage services', capability: 'Standards-based launches and configured grade return. Confirm enabled services during a pilot.', effort: 'Administrator registration and a test deployment', helpPath: '/docs/integrations/connecting-lms-with-lti-13', native: true },
  { slug: 'clever', name: 'Clever', version: 'No native connector currently documented', capability: 'Use supported SSO, roster exchange, or the public API only after an implementation review.', effort: 'Custom implementation; contact Lextures', helpPath: '/docs/integrations/using-webhooks', native: false },
  { slug: 'classlink', name: 'ClassLink', version: 'No native connector currently documented', capability: 'Use supported SSO, roster exchange, or the public API only after an implementation review.', effort: 'Custom implementation; contact Lextures', helpPath: '/docs/integrations/using-webhooks', native: false },
  { slug: 'powerschool-sis', name: 'PowerSchool SIS', version: 'No native connector currently documented', capability: 'Roster and grade exchange require a scoped implementation using supported APIs or files.', effort: 'Institution-led integration project', helpPath: '/docs/integrations/using-webhooks', native: false },
  { slug: 'infinite-campus', name: 'Infinite Campus', version: 'No native connector currently documented', capability: 'Roster and grade exchange require a scoped implementation using supported APIs or files.', effort: 'Institution-led integration project', helpPath: '/docs/integrations/using-webhooks', native: false },
  { slug: 'skyward', name: 'Skyward', version: 'No native connector currently documented', capability: 'Roster and grade exchange require a scoped implementation using supported APIs or files.', effort: 'Institution-led integration project', helpPath: '/docs/integrations/using-webhooks', native: false },
  { slug: 'google-workspace', name: 'Google Workspace', version: 'OIDC/OAuth deployment configuration', capability: 'Identity configuration is deployment-specific; Google Classroom course sync is not claimed.', effort: 'Administrator identity-provider setup and sign-in test', helpPath: '/docs/integrations/using-webhooks', native: false },
  { slug: 'microsoft-entra-id', name: 'Microsoft Entra ID', version: 'SAML 2.0, OIDC, and SCIM 2.0 where enabled', capability: 'Single sign-on and lifecycle provisioning can be configured for an institution.', effort: 'Identity administrator configuration and staged rollout', helpPath: '/docs/integrations/using-webhooks', native: true },
  { slug: 'canvas-migration', name: 'Canvas import and migration', version: 'No one-click native migration currently documented', capability: 'Plan an export review and staged content reconstruction; verify each assessment and grade artifact.', effort: 'Discovery, sample migration, validation, then cutover', helpPath: '/docs/integrations/connecting-lms-with-lti-13', native: false },
  { slug: 'zapier', name: 'Zapier', version: 'REST hooks and Lextures API v1', capability: 'Enrollment, grade, assignment, submission, and quiz triggers plus scoped actions when enabled.', effort: 'Enable features, create a scoped token, then connect a Zap', helpPath: '/docs/integrations/connecting-lextures-to-zapier', native: true },
  { slug: 'make', name: 'Make', version: 'REST hooks and Lextures API v1', capability: 'Uses the same supported triggers and actions as the Lextures automation connector when enabled.', effort: 'Enable features, create a scoped token, then build a scenario', helpPath: '/docs/integrations/using-lextures-with-make', native: true },
  { slug: 'webhooks-api', name: 'Webhooks and API', version: 'HTTPS REST API v1; HMAC-signed outbound webhooks', capability: 'Scoped API tokens and event subscriptions support institution-owned automations.', effort: 'Developer configuration, signature verification, and failure monitoring', helpPath: '/docs/integrations/using-webhooks', native: true },
]

export function getIntegration(slug: string) { return INTEGRATIONS.find(item => item.slug === slug) }
