/**
 * UX.8 — Classified pages (operations).
 * Part of classified-pages-data (TD.14 split).
 */

import type { ClassifiedPage } from './types'

const RBAC = 'rbac.manage'
const ACCOM = 'accommodations.manage'

export const CLASSIFIED_OPERATIONS_PAGES: ClassifiedPage[] = [
  // ── Operations (/admin/*) — non-configuration admin work ───────────
  {
    id: 'admin.overview',
    route: '/org-admin',
    scope: 'operations',
    label: 'Admin console',
    labelKey: 'nav.dest.adminOverview',
    requiredPermission: RBAC,
    featureFlag: 'adminConsoleEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.backup',
    route: '/admin/compliance/backup',
    scope: 'operations',
    label: 'Backup operations',
    labelKey: 'nav.dest.adminBackup',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.caption-compliance',
    route: '/admin/caption-compliance',
    scope: 'operations',
    label: 'Caption compliance',
    labelKey: 'nav.dest.adminCaptions',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.quarantine',
    route: '/admin/quarantine',
    scope: 'operations',
    label: 'File quarantine',
    labelKey: 'nav.dest.adminQuarantine',
    requiredPermission: RBAC,
    featureFlag: 'avScanningEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.iso',
    route: '/admin/compliance/iso',
    scope: 'operations',
    label: 'ISO compliance',
    labelKey: 'nav.dest.adminIso',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.security-reports',
    route: '/admin/compliance/security-reports',
    scope: 'operations',
    label: 'Security reports',
    labelKey: 'nav.dest.adminSecurityReports',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.banners',
    route: '/admin/banners',
    scope: 'operations',
    label: 'Notices',
    labelKey: 'nav.dest.adminBanners',
    requiredPermission: RBAC,
    featureFlag: 'maintenanceBannerEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.transcripts',
    route: '/admin/transcripts',
    scope: 'operations',
    label: 'Transcripts ops',
    labelKey: 'nav.dest.adminTranscripts',
    requiredPermission: RBAC,
    featureFlag: 'ffTranscripts',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.diplomas',
    route: '/admin/diplomas',
    scope: 'operations',
    label: 'Diplomas',
    labelKey: 'nav.dest.adminDiplomas',
    requiredPermission: RBAC,
    featureFlag: 'ffDiplomas',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.scheduled-jobs',
    route: '/admin/scheduled-jobs',
    scope: 'operations',
    label: 'Scheduled jobs',
    labelKey: 'nav.dest.adminScheduledJobs',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.boards',
    route: '/admin/boards',
    scope: 'operations',
    label: 'Collaboration boards',
    labelKey: 'nav.dest.adminBoards',
    requiredPermission: RBAC,
    featureFlag: 'ffVisualBoards',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.live-quizzes',
    route: '/admin/live-quizzes',
    scope: 'operations',
    label: 'Live Quizzes',
    labelKey: 'nav.dest.adminLiveQuizzes',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.webhooks',
    route: '/admin/webhooks',
    scope: 'operations',
    label: 'Webhooks',
    labelKey: 'nav.dest.adminWebhooks',
    requiredPermission: RBAC,
    featureFlag: 'ffWebhooks',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.email-templates-ops',
    route: '/admin/email-templates',
    scope: 'operations',
    label: 'Email templates (ops)',
    labelKey: 'nav.dest.adminEmailTemplates',
    requiredPermission: RBAC,
    featureFlag: 'emailTemplateEditorEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.ccr',
    route: '/admin/ccr/achievements',
    scope: 'operations',
    label: 'CCR achievements',
    labelKey: 'nav.dest.adminCcr',
    requiredPermission: ACCOM,
    featureFlag: 'ffCoCurricularTranscript',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.final-grades',
    route: '/admin/final-grades/status',
    scope: 'operations',
    label: 'Final grade status',
    labelKey: 'nav.dest.adminFinalGrades',
    requiredPermission: RBAC,
    featureFlag: 'ffGradeSubmission',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.incompletes',
    route: '/admin/incompletes',
    scope: 'operations',
    label: 'Incomplete grades',
    labelKey: 'nav.dest.adminIncompletes',
    requiredPermission: RBAC,
    featureFlag: 'ffIncompleteGradeWorkflow',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.demographics',
    route: '/admin/demographics/student',
    scope: 'operations',
    label: 'Student demographics',
    labelKey: 'nav.dest.adminDemographics',
    requiredPermission: RBAC,
    featureFlag: 'ffDemographics',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.title1',
    route: '/admin/demographics/title1',
    scope: 'operations',
    label: 'Title I report',
    labelKey: 'nav.dest.adminTitle1',
    requiredPermission: RBAC,
    featureFlag: 'ffDemographics',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.academic-calendar',
    route: '/admin/academic-calendar',
    scope: 'operations',
    label: 'Academic calendar',
    labelKey: 'nav.dest.adminAcademicCalendar',
    requiredPermission: RBAC,
    featureFlag: 'ffAcademicCalendar',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.attendance-dashboard',
    route: '/admin/attendance/dashboard',
    scope: 'operations',
    label: 'Attendance dashboard',
    labelKey: 'nav.dest.adminAttendance',
    requiredPermission: RBAC,
    featureFlag: 'ffClassroomSignals',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.attendance-export',
    route: '/admin/attendance/export',
    scope: 'operations',
    label: 'Attendance export',
    labelKey: 'nav.dest.adminAttendanceExport',
    requiredPermission: RBAC,
    featureFlag: 'ffClassroomSignals',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.behavior',
    route: '/admin/behavior/dashboard',
    scope: 'operations',
    label: 'Behavior dashboard',
    labelKey: 'nav.dest.adminBehavior',
    requiredPermission: RBAC,
    featureFlag: 'ffClassroomSignals',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.broadcasts',
    route: '/admin/broadcasts',
    scope: 'operations',
    label: 'Broadcasts',
    labelKey: 'nav.dest.adminBroadcasts',
    requiredPermission: RBAC,
    featureFlag: 'ffBroadcasts',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.conferences',
    route: '/admin/conferences/schedule',
    scope: 'operations',
    label: 'Conference schedule',
    labelKey: 'nav.dest.adminConferences',
    requiredPermission: RBAC,
    featureFlag: 'ffConferenceScheduling',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.eval-report',
    route: '/admin/evaluations/report',
    scope: 'operations',
    label: 'Evaluation report',
    labelKey: 'nav.dest.adminEvalReport',
    requiredPermission: RBAC,
    featureFlag: 'ffCourseEvaluations',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.eval-templates',
    route: '/admin/evaluations/templates',
    scope: 'operations',
    label: 'Evaluation templates',
    labelKey: 'nav.dest.adminEvalTemplates',
    requiredPermission: RBAC,
    featureFlag: 'ffCourseEvaluations',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.content-tools',
    route: '/admin/content-tools',
    scope: 'operations',
    label: 'Content tools',
    labelKey: 'nav.dest.adminContentTools',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.reviews',
    route: '/admin/reviews',
    scope: 'operations',
    label: 'Course reviews',
    labelKey: 'nav.dest.adminReviews',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.tool-reviews',
    route: '/admin/tool-reviews',
    scope: 'operations',
    label: 'Tool reviews',
    labelKey: 'nav.dest.adminToolReviews',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.licenses',
    route: '/admin/licenses',
    scope: 'operations',
    label: 'Licenses',
    labelKey: 'nav.dest.adminLicenses',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.accommodations',
    route: '/admin/accommodations',
    scope: 'operations',
    label: 'Accommodations',
    labelKey: 'nav.dest.adminAccommodations',
    requiredPermission: ACCOM,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.tax',
    route: '/admin/tax',
    scope: 'operations',
    label: 'Tax settings',
    labelKey: 'nav.dest.adminTax',
    requiredPermission: RBAC,
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.audit-log',
    route: '/org-admin/audit',
    scope: 'operations',
    label: 'Audit log',
    labelKey: 'nav.dest.adminAudit',
    requiredPermission: RBAC,
    featureFlag: 'adminConsoleEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.import',
    route: '/org-admin/import',
    scope: 'operations',
    label: 'Import',
    labelKey: 'nav.dest.adminImport',
    requiredPermission: RBAC,
    featureFlag: 'adminConsoleEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.users',
    route: '/org-admin/users',
    scope: 'operations',
    label: 'Users',
    labelKey: 'nav.dest.adminUsers',
    requiredPermission: RBAC,
    featureFlag: 'adminConsoleEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
  {
    id: 'admin.courses-console',
    route: '/org-admin/courses',
    scope: 'operations',
    label: 'Courses (console)',
    labelKey: 'nav.dest.adminCourses',
    requiredPermission: RBAC,
    featureFlag: 'adminConsoleEnabled',
    section: 'admin-tools',
    kind: 'operations',
  },
]
