/**
 * UX.8 — Classified pages (me / organisation / platform configuration).
 * Part of classified-pages-data (TD.14 split).
 */

import type { ClassifiedPage } from './types'

const RBAC = 'rbac.manage'
const ORG_UNITS = 'tenant.org_units.admin'

export const CLASSIFIED_CONFIG_PAGES: ClassifiedPage[] = [
  // ── Me (user settings) ──────────────────────────────────────────────
  {
    id: 'settings.account',
    route: '/settings/account',
    scope: 'me',
    label: 'Account',
    labelKey: 'nav.dest.settingsAccount',
    description: 'Profile, password, MFA, sessions, and locale',
    requiredPermission: null,
    section: 'user-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.integrations',
    route: '/settings/integrations',
    scope: 'me',
    label: 'Integrations',
    labelKey: 'nav.dest.settingsIntegrations',
    description: 'Personal access keys, calendar feeds, and MCP',
    requiredPermission: null,
    section: 'user-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.learner-profile',
    route: '/settings/learner-profile',
    scope: 'me',
    label: 'Learner Profile',
    labelKey: 'nav.dest.settingsLearnerProfile',
    requiredPermission: null,
    featureFlag: 'learnerProfileEnabled',
    section: 'user-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.notifications',
    route: '/settings/notifications',
    scope: 'me',
    label: 'Notifications',
    labelKey: 'nav.dest.settingsNotifications',
    requiredPermission: null,
    section: 'user-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.privacy-centre',
    route: '/privacy-centre',
    scope: 'me',
    label: 'Privacy Center',
    labelKey: 'nav.dest.settingsPrivacy',
    requiredPermission: null,
    featureFlag: 'gdprModuleEnabled',
    section: 'user-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.study-reminders',
    route: '/settings/account',
    scope: 'me',
    label: 'Study reminders',
    labelKey: 'nav.dest.settingsStudyReminders',
    requiredPermission: null,
    section: 'user-settings',
    kind: 'configuration',
  },

  // ── Organisation configuration ─────────────────────────────────────
  {
    id: 'settings.terms',
    route: '/settings/terms',
    scope: 'org',
    label: 'Academic terms',
    labelKey: 'nav.dest.settingsTerms',
    requiredPermission: ORG_UNITS,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.advising',
    route: '/settings/advising',
    scope: 'org',
    label: 'Advising',
    labelKey: 'nav.dest.settingsAdvising',
    requiredPermission: RBAC,
    featureFlag: 'ffAdvisingIntegration',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.archive',
    route: '/settings/archive',
    scope: 'org',
    label: 'Archive',
    labelKey: 'nav.dest.settingsArchive',
    requiredPermission: RBAC,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.bookstore',
    route: '/settings/org/bookstore',
    legacyRoute: '/admin/bookstore',
    scope: 'org',
    label: 'Bookstore',
    labelKey: 'nav.dest.settingsBookstore',
    requiredPermission: RBAC,
    featureFlag: 'ffBookstoreIntegration',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.org-branding',
    route: '/settings/org-branding',
    scope: 'org',
    label: 'Branding',
    labelKey: 'nav.dest.settingsBranding',
    requiredPermission: ORG_UNITS,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.consortium',
    route: '/settings/org/consortium',
    legacyRoute: '/admin/consortium',
    scope: 'org',
    label: 'Consortium sharing',
    labelKey: 'nav.dest.settingsConsortium',
    requiredPermission: RBAC,
    featureFlag: 'ffConsortiumSharing',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.courses',
    route: '/settings/courses',
    scope: 'org',
    label: 'Courses',
    labelKey: 'nav.dest.settingsCourses',
    requiredPermission: RBAC,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.email-templates',
    route: '/settings/email-templates',
    scope: 'org',
    label: 'Email templates',
    labelKey: 'nav.dest.settingsEmailTemplates',
    requiredPermission: RBAC,
    featureFlag: 'emailTemplateEditorEnabled',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.feedback',
    route: '/settings/feedback',
    scope: 'org',
    label: 'Feedback',
    labelKey: 'nav.dest.settingsFeedback',
    requiredPermission: RBAC,
    featureFlag: 'ffFeedback',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.intro-course',
    route: '/settings/intro-course',
    scope: 'org',
    label: 'Intro course',
    labelKey: 'nav.dest.settingsIntroCourse',
    requiredPermission: RBAC,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.accessibility',
    route: '/settings/org/accessibility',
    legacyRoute: '/admin/accessibility',
    scope: 'org',
    label: 'Accessibility services',
    labelKey: 'nav.dest.settingsAccessibility',
    requiredPermission: RBAC,
    featureFlag: 'ffAccessibilityIntake',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.content-filter',
    route: '/settings/org/content-filter',
    legacyRoute: '/admin/content-filter',
    scope: 'org',
    label: 'Content filter',
    labelKey: 'nav.dest.settingsContentFilter',
    requiredPermission: RBAC,
    featureFlag: 'ffContentFilterIntegration',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.org-units',
    route: '/settings/org-units',
    scope: 'org',
    label: 'Org structure',
    labelKey: 'nav.dest.settingsOrgUnits',
    requiredPermission: ORG_UNITS,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.organizations',
    route: '/settings/organizations',
    scope: 'org',
    label: 'Organizations',
    labelKey: 'nav.dest.settingsOrganizations',
    requiredPermission: RBAC,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.people',
    route: '/settings/people',
    scope: 'org',
    label: 'People',
    labelKey: 'nav.dest.settingsPeople',
    requiredPermission: RBAC,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.consent-studies',
    route: '/settings/org/consent-studies',
    legacyRoute: '/admin/consent-studies',
    scope: 'org',
    label: 'Research consent',
    labelKey: 'nav.dest.settingsConsentStudies',
    requiredPermission: RBAC,
    featureFlag: 'ffResearchConsent',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.roles',
    route: '/settings/roles',
    scope: 'org',
    label: 'Roles and Permissions',
    labelKey: 'nav.dest.settingsRoles',
    requiredPermission: RBAC,
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.scim',
    route: '/settings/scim-provisioning',
    scope: 'org',
    label: 'SCIM provisioning',
    labelKey: 'nav.dest.settingsScim',
    requiredPermission: RBAC,
    featureFlag: 'scimEnabled',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.sis',
    route: '/settings/org/sis',
    legacyRoute: '/admin/sis',
    scope: 'org',
    label: 'SIS integration',
    labelKey: 'nav.dest.settingsSis',
    requiredPermission: RBAC,
    featureFlag: 'ffSisIntegration',
    section: 'org-settings',
    kind: 'configuration',
  },
  {
    id: 'settings.transcripts',
    route: '/settings/transcripts',
    scope: 'org',
    label: 'Transcripts',
    labelKey: 'nav.dest.settingsTranscripts',
    requiredPermission: RBAC,
    featureFlag: 'ffTranscripts',
    section: 'org-settings',
    kind: 'configuration',
  },

  // ── Platform configuration ─────────────────────────────────────────
  {
    id: 'settings.platform',
    route: '/settings/platform',
    scope: 'platform',
    label: 'Global platform',
    labelKey: 'nav.dest.settingsPlatform',
    description: 'Feature flags and deployment-wide configuration',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.cloud-providers',
    route: '/settings/cloud-providers',
    scope: 'platform',
    label: 'Cloud file pickers',
    labelKey: 'nav.dest.settingsCloudProviders',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.ai-models',
    route: '/settings/ai/models',
    scope: 'platform',
    label: 'AI Models',
    labelKey: 'nav.dest.settingsAiModels',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.ai-governance',
    route: '/settings/ai/governance',
    scope: 'platform',
    label: 'AI Governance',
    labelKey: 'nav.dest.settingsAiGovernance',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.ai-reports',
    route: '/settings/ai/reports',
    scope: 'platform',
    label: 'AI Reports',
    labelKey: 'nav.dest.settingsAiReports',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.ai-prompts',
    route: '/settings/ai/system-prompts',
    scope: 'platform',
    label: 'System Prompts',
    labelKey: 'nav.dest.settingsAiPrompts',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.lrs',
    route: '/settings/lrs-integrations',
    scope: 'platform',
    label: 'Learning Record Stores',
    labelKey: 'nav.dest.settingsLrs',
    requiredPermission: RBAC,
    featureFlag: 'xapiEmissionEnabled',
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.lti-tools',
    route: '/settings/lti-tools',
    scope: 'platform',
    label: 'LTI tools',
    labelKey: 'nav.dest.settingsLti',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.oer',
    route: '/settings/oer-providers',
    scope: 'platform',
    label: 'OER library',
    labelKey: 'nav.dest.settingsOer',
    requiredPermission: RBAC,
    featureFlag: 'oerLibraryEnabled',
    section: 'platform',
    kind: 'configuration',
  },
  {
    id: 'settings.integrations-admin',
    route: '/settings/platform/integrations',
    legacyRoute: '/admin/integrations',
    scope: 'platform',
    label: 'Integrations',
    labelKey: 'nav.dest.settingsPlatformIntegrations',
    requiredPermission: RBAC,
    section: 'platform',
    kind: 'configuration',
  },
]
