/**
 * E2E.2 — single source of truth for platform feature flag contract metadata.
 *
 * Every key in PLATFORM_FEATURE_DEFINITIONS must appear here.
 * Register new platform flags here when adding a Global platform toggle.
 * UI labels must match platform-feature-definitions.ts exactly.
 */

export type PlatformFeatureOwnership = 'database' | 'environment'

export type PlatformFeatureCategory =
  | 'accessibility'
  | 'admin'
  | 'ai'
  | 'analytics'
  | 'boards'
  | 'commerce'
  | 'grading'
  | 'identity'
  | 'integration'
  | 'learner'
  | 'platform'
  | 'quizzes'
  | 'transcripts'

export type PlatformFeatureMatrixEntry = {
  key: string
  /** Settings row label — must match PLATFORM_FEATURE_DEFINITIONS. */
  label: string
  category: PlatformFeatureCategory
  /**
   * database — mutable via PUT /settings/platform (Global platform toggles).
   * environment — process-env owned; UI must be read-only (none of the boolean
   * definitions are environment-owned today; reserved for contract coverage).
   */
  ownershipSource: PlatformFeatureOwnership
  /** Maps into PlatformSettingsPayload.sources when the API reports field provenance. */
  sourceKey: string | null
  /** Key on GET /api/v1/platform/features, or null when settings-only. */
  runtimeKey: string | null
  /** Required when runtimeKey is null — documents intentional settings-only flags. */
  settingsOnlyRationale: string | null
  /** Never log or round-trip secret values for this key (booleans are false). */
  secretSensitive: boolean
  /** Include in the representative Global platform UI sample suite. */
  uiSample: boolean
  /** Optional gated surface hint for operators (not asserted by the contract suite). */
  gatedSurface: string | null
}

export const PLATFORM_FEATURE_MATRIX: readonly PlatformFeatureMatrixEntry[] = [
  {
    key: 'accommodationsEngineEnabled',
    label: 'Accommodations engine',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'accommodationsEngineEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'adminConsoleEnabled',
    label: 'Admin console',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'adminConsoleEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'adminSearchEnabled',
    label: 'Admin org-wide search',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'adminSearchEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'annotationEnabled',
    label: 'Annotations',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'annotationEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Grading/content annotation is settings-gated; not exposed on /platform/features',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'atRiskAlertsEnabled',
    label: 'At-risk early-warning alerts',
    category: 'analytics',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'atRiskAlertsEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'avScanningEnabled',
    label: 'Antivirus scanning',
    category: 'platform',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'avScanningEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'badgesDefaultPublic',
    label: 'New badges public by default',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Badge visibility default is settings-only configuration',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'blindGradingEnabled',
    label: 'Blind grading',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'blindGradingEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Grading workflow setting; not a runtime feature payload field',
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'bulkCsvImportEnabled',
    label: 'Bulk user CSV import',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'bulkCsvImportEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'codeExecutionEnabled',
    label: 'Code execution',
    category: 'ai',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'codeExecutionEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'customFieldsEnabled',
    label: 'Custom fields',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Org custom fields are settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'emailTemplateEditorEnabled',
    label: 'Email template editor',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'emailTemplateEditorEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'equationEditorEnabled',
    label: 'Equation editor',
    category: 'ai',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'equationEditorEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'feedbackMediaEnabled',
    label: 'Feedback media',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'feedbackMediaEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Grading media feedback setting; not in runtime payload',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffAcademicCalendar',
    label: 'Academic calendar',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffAcademicCalendar',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffAccessibilityIntake',
    label: 'Accessibility services intake',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffAccessibilityIntake',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffAccommodationsEngine',
    label: 'Accommodations audit log',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffAccommodationsEngine',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffAdvisingIntegration',
    label: 'Advising integration',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffAdvisingIntegration',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffAiStudyBuddy',
    label: 'AI study buddy',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffAiStudyBuddy',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffAltTextEnforcement',
    label: 'Alt-text hard block',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffAltTextEnforcement',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'ffApiTokens',
    label: 'API access keys',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'API token issuance is settings-only admin control',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffBoardsExternalSharing',
    label: 'Board external sharing',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffBoardsExternalSharing',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffBoardsRealtime',
    label: 'Board realtime sync',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffBoardsRealtime',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffBookstoreIntegration',
    label: 'Bookstore / textbook integration',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffBookstoreIntegration',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'ffBotDiscord',
    label: 'Discord classroom bot',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Bot connector credentials live outside runtime feature snapshot',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffBotSlack',
    label: 'Slack classroom bot',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Bot connector credentials live outside runtime feature snapshot',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffBotTeams',
    label: 'Microsoft Teams classroom bot',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Bot connector credentials live outside runtime feature snapshot',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffBroadcasts',
    label: 'Institution broadcasts',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffBroadcasts',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCalendarFeeds',
    label: 'Calendar feeds',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCalendarFeeds',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCatalogIntegration',
    label: 'Course catalog & registration',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCatalogIntegration',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCeuTracking',
    label: 'CEU seat-time tracking',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCeuTracking',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffClassroomSignals',
    label: 'Classroom signals',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffClassroomSignals',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCoCurricularTranscript',
    label: 'Co-curricular transcript (CLR)',
    category: 'transcripts',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCoCurricularTranscript',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCompetencyBadges',
    label: 'Competency micro-badges',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCompetencyBadges',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCompletionCredentials',
    label: 'Completion certificates (Open Badges)',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCompletionCredentials',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffConditionalRelease',
    label: 'Conditional release & module requirements',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffConditionalRelease',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffConferenceScheduling',
    label: 'Parent-teacher conferences',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffConferenceScheduling',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffConsortiumSharing',
    label: 'Consortium course sharing',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffConsortiumSharing',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCourseEvaluations',
    label: 'Course evaluations',
    category: 'platform',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCourseEvaluations',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCourseMarketplace',
    label: 'Course marketplace',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCourseMarketplace',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffCourseReviews',
    label: 'Course reviews',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffCourseReviews',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffDemographics',
    label: 'Student demographics reporting',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffDemographics',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffDiplomas',
    label: 'Diplomas & certificates',
    category: 'transcripts',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffDiplomas',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffEmailSes',
    label: 'Amazon SES email provider',
    category: 'ai',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffEmailSes',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffEnrollmentStateMachine',
    label: 'Enrollment lifecycle',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffEnrollmentStateMachine',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffEportfolio',
    label: 'ePortfolio / capstone artifacts',
    category: 'transcripts',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffEportfolio',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffFeedback',
    label: 'In-app product feedback',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffFeedback',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffGamification',
    label: 'Gamification & leaderboards',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffGamification',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffGradeCurving',
    label: 'Grade curving',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffGradeCurving',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffGradeSubmission',
    label: 'Final grade submission',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffGradeSubmission',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIncompleteGradeWorkflow',
    label: 'Incomplete grade workflow',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIncompleteGradeWorkflow',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIqAiGeneration',
    label: 'Live quiz AI generation',
    category: 'ai',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqAiGeneration',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIqGradebookPush',
    label: 'Live quiz gradebook push',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqGradebookPush',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIqGuestJoin',
    label: 'Live quiz guest join',
    category: 'quizzes',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqGuestJoin',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIqHomework',
    label: 'Live quiz homework',
    category: 'quizzes',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqHomework',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIqLiveHosting',
    label: 'Live quiz hosting',
    category: 'quizzes',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqLiveHosting',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'ffIqPublicKitCatalog',
    label: 'Live quiz public kit catalog',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqPublicKitCatalog',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIqStudentPaced',
    label: 'Live quiz student-paced mode',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqStudentPaced',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffIqTeamMode',
    label: 'Live quiz team mode',
    category: 'quizzes',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffIqTeamMode',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffLearningPaths',
    label: 'Learning paths / bundles',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffLearningPaths',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'ffLessonGenerator',
    label: 'AI lesson generator',
    category: 'ai',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffLessonGenerator',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffLibrary',
    label: 'Learner library & reading log',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffLibrary',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffLibraryIntegration',
    label: 'Library system integration',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffLibraryIntegration',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffMotionLists',
    label: 'List & collection motion',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffMotionLists',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffMotionNavigation',
    label: 'Navigation transitions',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffMotionNavigation',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffMotionReveal',
    label: 'Load choreography',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffMotionReveal',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffOnboardingFlow',
    label: 'Self-learner onboarding',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffOnboardingFlow',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffParentPortal',
    label: 'Parent portal',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffParentPortal',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffParentPortalV2',
    label: 'Parent portal v2 sections',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffParentPortalV2',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffPaymentsEnabled',
    label: 'Payment provider abstraction',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffPaymentsEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffPeerReview',
    label: 'Peer review & assessment',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffPeerReview',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffPersistentTutor',
    label: 'Persistent AI tutor',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffPersistentTutor',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffProctoringIntegration',
    label: 'Proctoring integration',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffProctoringIntegration',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffPublicApi',
    label: 'Public REST API',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Public API surface is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffPublicCatalog',
    label: 'Public course catalog',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Catalog publication is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffReadAloud',
    label: 'Read-aloud (text-to-speech)',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffReadAloud',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffReadingPreferences',
    label: 'Reading preferences',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffReadingPreferences',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffRedisCache',
    label: 'Redis object cache',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Infrastructure cache toggle is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffReportCards',
    label: 'Report cards',
    category: 'platform',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffReportCards',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffResearchConsent',
    label: 'Research / IRB consent',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffResearchConsent',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffRevenueShare',
    label: 'Creator revenue share & affiliates',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffRevenueShare',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffSelfPacedMode',
    label: 'Self-paced course mode',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Course pacing default is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffSisIntegration',
    label: 'SIS integration',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffSisIntegration',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffStripeBilling',
    label: 'Stripe billing (self-learner)',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffStripeBilling',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffTaxCollection',
    label: 'Tax collection (Stripe Tax)',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffTaxCollection',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffTranscriptInbound',
    label: 'Transcript inbound intake',
    category: 'transcripts',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffTranscriptInbound',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffTranscripts',
    label: 'Transcripts',
    category: 'transcripts',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffTranscripts',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'ffUiMode',
    label: 'UI mode switcher',
    category: 'platform',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffUiMode',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffVisualBoards',
    label: 'Collaboration boards',
    category: 'boards',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffVisualBoards',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'ffWebhooks',
    label: 'Outbound webhooks',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffWebhooks',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'ffWhatifGrades',
    label: 'What-if grades',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffWhatifGrades',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ffZapierConnector',
    label: 'Zapier / Make connector',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'ffZapierConnector',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'gradebookCsvEnabled',
    label: 'Gradebook CSV export',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'gradebookCsvEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Gradebook export capability is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'gradePostingPoliciesEnabled',
    label: 'Grade posting policies',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'gradePostingPoliciesEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Grade posting policy is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentCancelRunEnabled',
    label: 'Grader agent cancel run',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentCancelRunEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentCostEstimateEnabled',
    label: 'Grader agent cost estimate',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentCostEstimateEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentEnabled',
    label: 'Grader agent',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentReviewInboxEnabled',
    label: 'Grader agent review inbox',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentReviewInboxEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentRunFiltersEnabled',
    label: 'Grader agent run filters',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentRunFiltersEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentSuggestModeEnabled',
    label: 'Grader agent suggest mode',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentSuggestModeEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentTextEntryGradingEnabled',
    label: 'Grader agent text-entry grading',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentTextEntryGradingEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'graderAgentVisionGradingEnabled',
    label: 'Grader agent vision grading',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'graderAgentVisionGradingEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'h5pEnabled',
    label: 'Interactive H5P content',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'h5pEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'impersonationEnabled',
    label: 'Admin impersonation',
    category: 'identity',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'impersonationEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'introCourseEnabled',
    label: 'Intro course ("Welcome to Lextures")',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'introCourseEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'itemAnalysisEnabled',
    label: 'Quiz item analysis',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'itemAnalysisEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'learnerProfileEnabled',
    label: 'Learner profile',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'learnerProfileEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'lpAdaptModalityEnabled',
    label: 'Profile adaptivity — content modality',
    category: 'platform',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Learner-profile adaptivity sub-flag; settings-only until runtime wiring',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'lpAdaptRecommendationsEnabled',
    label: 'Profile adaptivity — recommendations',
    category: 'platform',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Learner-profile adaptivity sub-flag; settings-only until runtime wiring',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'lpAdaptReviewEnabled',
    label: 'Profile adaptivity — review queue',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Learner-profile adaptivity sub-flag; settings-only until runtime wiring',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'lpAdaptTutorEnabled',
    label: 'Profile adaptivity — AI tutor',
    category: 'ai',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'Learner-profile adaptivity sub-flag; settings-only until runtime wiring',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'ltiEnabled',
    label: 'LTI',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: 'ltiEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'LTI enablement is settings-only (launch paths check config directly)',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'maintenanceBannerEnabled',
    label: 'Maintenance banners',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'maintenanceBannerEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'mfaEnabled',
    label: 'Two-factor authentication',
    category: 'identity',
    ownershipSource: 'database',
    sourceKey: 'mfaEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'MFA enablement is settings-only (auth paths check config directly)',
    secretSensitive: false,
    uiSample: true,
    gatedSurface: null,
  },
  {
    key: 'moderatedGradingEnabled',
    label: 'Moderated grading',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'moderatedGradingEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Grading workflow setting; not in runtime payload',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'oerLibraryEnabled',
    label: 'OER library search',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'oerLibraryEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'oerStub',
    label: 'OER stub catalog',
    category: 'commerce',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: null,
    settingsOnlyRationale: 'OER stub mode is settings-only diagnostic',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'oneRosterEnabled',
    label: 'OneRoster API',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: 'oneRosterEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'OneRoster enablement is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'originalityDetectionEnabled',
    label: 'Originality detection',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'originalityDetectionEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Originality setting; not in runtime payload',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'originalityStubExternal',
    label: 'Originality stub external',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'originalityStubExternal',
    runtimeKey: null,
    settingsOnlyRationale: 'Originality stub mode is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'outcomesReportEnabled',
    label: 'Course outcomes report',
    category: 'analytics',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'outcomesReportEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'readingLevelEnabled',
    label: 'Reading level adaptation',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'readingLevelEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'resubmissionWorkflowEnabled',
    label: 'Resubmission workflow',
    category: 'grading',
    ownershipSource: 'database',
    sourceKey: 'resubmissionWorkflowEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'Resubmission workflow is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'scimEnabled',
    label: 'SCIM 2.0 provisioning',
    category: 'identity',
    ownershipSource: 'database',
    sourceKey: 'scimEnabled',
    runtimeKey: null,
    settingsOnlyRationale: 'SCIM enablement is settings-only',
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'scormIngestionEnabled',
    label: 'SCORM / cmi5 ingestion',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'scormIngestionEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'seatManagementEnabled',
    label: 'Seat license management',
    category: 'admin',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'seatManagementEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'selfReflectionEnabled',
    label: 'Learner self-reflection & coaching',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'selfReflectionEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'sessionManagementUiEnabled',
    label: 'Active sessions UI',
    category: 'identity',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'sessionManagementUiEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'speechToTextEnabled',
    label: 'Speech-to-text dictation',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'speechToTextEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'storageQuotasEnabled',
    label: 'Storage quotas',
    category: 'ai',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'storageQuotasEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'studentProgressEnabled',
    label: 'Per-student progress dashboards',
    category: 'learner',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'studentProgressEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'translationMemoryEnabled',
    label: 'Translation memory',
    category: 'accessibility',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'translationMemoryEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'virtualClassroomEnabled',
    label: 'Virtual classroom',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'virtualClassroomEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
  {
    key: 'xapiEmissionEnabled',
    label: 'xAPI / Caliper emission',
    category: 'integration',
    ownershipSource: 'database',
    sourceKey: null,
    runtimeKey: 'xapiEmissionEnabled',
    settingsOnlyRationale: null,
    secretSensitive: false,
    uiSample: false,
    gatedSurface: null,
  },
] as const

export const ALL_PLATFORM_FEATURE_KEYS: readonly string[] = PLATFORM_FEATURE_MATRIX.map((e) => e.key)

export const DATABASE_OWNED_PLATFORM_FEATURES = PLATFORM_FEATURE_MATRIX.filter(
  (e) => e.ownershipSource === 'database',
)

export const ENVIRONMENT_OWNED_PLATFORM_FEATURES = PLATFORM_FEATURE_MATRIX.filter(
  (e) => e.ownershipSource === 'environment',
)

export const UI_SAMPLE_PLATFORM_FEATURES = PLATFORM_FEATURE_MATRIX.filter((e) => e.uiSample)

export const PLATFORM_FEATURE_CATEGORIES: readonly PlatformFeatureCategory[] = [
  'accessibility',
  'admin',
  'ai',
  'analytics',
  'boards',
  'commerce',
  'grading',
  'identity',
  'integration',
  'learner',
  'platform',
  'quizzes',
  'transcripts',
]

/** Boolean keys snapshotted/restored by platform contract helpers (never secrets). */
export const PLATFORM_BOOLEAN_SNAPSHOT_KEYS: readonly string[] = ALL_PLATFORM_FEATURE_KEYS

/**
 * Parse PLATFORM_FEATURE_DEFINITIONS keys from the web source (for parity tests).
 */
export function parsePlatformFeatureDefinitionKeys(source: string): string[] {
  const keys: string[] = []
  // Match definition entries only (`key: '…'`), not `sourceKey:`.
  const re = /^\s*key:\s*'([^']+)'/gm
  for (const match of source.matchAll(re)) {
    keys.push(match[1])
  }
  return keys
}

/** Validate matrix uniqueness and required metadata (unit-level). */
export function validatePlatformFeatureMatrix(definitionKeys?: readonly string[]): string[] {
  const errors: string[] = []
  const keys = new Set<string>()
  const labels = new Set<string>()

  for (const entry of PLATFORM_FEATURE_MATRIX) {
    if (keys.has(entry.key)) errors.push(`duplicate key: ${entry.key}`)
    keys.add(entry.key)

    if (labels.has(entry.label)) errors.push(`duplicate label: ${entry.label}`)
    labels.add(entry.label)

    if (!entry.label.trim()) errors.push(`${entry.key} missing label`)
    if (!entry.category) errors.push(`${entry.key} missing category`)

    if (entry.ownershipSource !== 'database' && entry.ownershipSource !== 'environment') {
      errors.push(`${entry.key} invalid ownershipSource`)
    }

    if (entry.runtimeKey == null) {
      if (!entry.settingsOnlyRationale?.trim()) {
        errors.push(`${entry.key} settings-only flag missing settingsOnlyRationale`)
      }
    } else if (entry.settingsOnlyRationale != null) {
      errors.push(`${entry.key} has runtimeKey but also settingsOnlyRationale`)
    }

    if (entry.secretSensitive) {
      errors.push(`${entry.key}: boolean matrix entries must not be secretSensitive`)
    }
  }

  if (definitionKeys) {
    const defSet = new Set(definitionKeys)
    for (const key of definitionKeys) {
      if (!keys.has(key)) {
        errors.push(`definition key missing from manifest: ${key}`)
      }
    }
    for (const key of keys) {
      if (!defSet.has(key)) {
        errors.push(`manifest key not in PLATFORM_FEATURE_DEFINITIONS: ${key}`)
      }
    }
    if (definitionKeys.length !== PLATFORM_FEATURE_MATRIX.length) {
      errors.push(
        `definition/manifest count mismatch: defs=${definitionKeys.length} manifest=${PLATFORM_FEATURE_MATRIX.length}`,
      )
    }
  }

  // Exactly one UI sample per category
  for (const cat of PLATFORM_FEATURE_CATEGORIES) {
    const samples = PLATFORM_FEATURE_MATRIX.filter((e) => e.category === cat && e.uiSample)
    if (samples.length !== 1) {
      errors.push(`category ${cat} expected 1 uiSample, got ${samples.length}`)
    }
  }

  return errors
}

export function entriesForCategory(category: PlatformFeatureCategory) {
  return PLATFORM_FEATURE_MATRIX.filter((e) => e.category === category)
}

export function apiContractShards(shardCount = 3): PlatformFeatureMatrixEntry[][] {
  const owned = DATABASE_OWNED_PLATFORM_FEATURES
  const shards: PlatformFeatureMatrixEntry[][] = Array.from({ length: shardCount }, () => [])
  owned.forEach((entry, i) => {
    shards[i % shardCount]!.push(entry)
  })
  return shards
}
