import { useMemo, useState } from 'react'
import { MarketingPageShell, AudienceHero } from '../components/marketing-page-shell'
import { GLOSSARY_TERMS, STANDARDS, TEMPLATES, getGlossaryTerm, getStandard, getTemplate } from '../data/utility-content'

function UtilityLinks() {
  return <aside className="mt-12 rounded-[18px] border p-6" style={{ borderColor: 'var(--line-card)', background: 'var(--panel)' }}>
    <h2 className="font-display text-xl font-semibold">Keep exploring</h2>
    <ul className="mt-3 flex flex-wrap gap-x-6 gap-y-2"><li><a href="/platform/assessment">Assessment platform</a></li><li><a href="/docs">Implementation help</a></li><li><a href="/resources">Learning resources</a></li></ul>
  </aside>
}

export function GlossaryIndexPage() {
  return <MarketingPageShell><AudienceHero eyebrow="Resources" title="Learning and assessment glossary" lead="Reviewed, sourced definitions with examples and practical decisions—not dictionary stubs." primaryHref="/tools" primaryLabel="Try free tools" secondaryHref="/resources" secondaryLabel="All resources" />
    <main className="mx-auto max-w-[960px] px-5 py-14 md:px-10"><p className="max-w-3xl leading-relaxed">Browse concepts used in assessment, adaptive learning, instructional design, accessibility, and learning technology. Each entry includes a copyable definition, a worked example, related concepts, and a practical way to decide whether the idea applies.</p><ul className="mt-8 grid gap-4 md:grid-cols-2">{GLOSSARY_TERMS.map(term => <li key={term.slug} className="rounded-[16px] border p-5" style={{ borderColor: 'var(--line-card)', background: 'var(--panel)' }}><p className="text-sm" style={{ color: 'var(--text-soft)' }}>{term.category}</p><h2 className="font-display mt-1 text-xl font-semibold"><a href={`/glossary/${term.slug}`}>{term.term}</a></h2><p className="mt-2 leading-relaxed">{term.sentence}</p></li>)}</ul><UtilityLinks /></main>
  </MarketingPageShell>
}

export function GlossaryTermPage({ term: slug }: { term: string }) {
  const item = getGlossaryTerm(slug)
  if (!item) return null
  const copy = () => navigator.clipboard?.writeText(item.definition)
  return <MarketingPageShell><main className="mx-auto max-w-[880px] px-5 py-14 md:px-10"><nav aria-label="Breadcrumb"><a href="/glossary">Glossary</a> / {item.term}</nav><p className="mt-8 text-sm font-semibold uppercase tracking-wide" style={{ color: 'var(--coral)' }}>{item.category}</p><h1 className="font-display mt-2 text-4xl font-semibold">{item.term}</h1>
    <section className="mt-8 rounded-[18px] border p-6" style={{ borderColor: 'var(--line-card)', background: 'var(--panel)' }} aria-labelledby="definition-heading"><h2 id="definition-heading" className="font-display text-2xl font-semibold">Definition</h2><p className="mt-3 text-lg leading-relaxed">{item.definition}</p><button type="button" onClick={copy} className="btn-secondary mt-5">Copy definition</button></section>
    <section className="mt-10"><h2 className="font-display text-2xl font-semibold">In one sentence</h2><p className="mt-3 text-lg leading-relaxed">{item.sentence}</p></section>
    <section className="mt-10"><h2 className="font-display text-2xl font-semibold">Worked example</h2><p className="mt-3 leading-relaxed">{item.example}</p></section>
    <section className="mt-10"><h2 className="font-display text-2xl font-semibold">How to use the idea</h2><p className="mt-3 leading-relaxed">{item.substance}</p><p className="mt-4">In Lextures, explore <a href={item.lexturesHref}>{item.lexturesLabel}</a>.</p></section>
    <section className="mt-10"><h2 className="font-display text-2xl font-semibold">Related terms</h2><ul className="mt-3 flex flex-wrap gap-4">{item.related.map(related => <li key={related}><a href={`/glossary/${related}`}>{getGlossaryTerm(related)?.term ?? related.replaceAll('-', ' ')}</a></li>)}</ul></section>
    <section className="mt-10"><h2 className="font-display text-2xl font-semibold">Sources and review</h2><ul className="mt-3">{item.sources.map(source => <li key={source.href}><a href={source.href} rel="noreferrer">{source.label}</a></li>)}</ul><p className="mt-3 text-sm">Reviewed by <a href={`/authors/${item.reviewedBy}`}>Chase Willden</a> on <time dateTime={item.reviewedAt}>{item.reviewedAt}</time>.</p></section><UtilityLinks /></main></MarketingPageShell>
}

export function StandardsIndexPage() {
  return <MarketingPageShell><AudienceHero eyebrow="United States frameworks" title="Academic standards browser" lead="Browse official standards references alongside original mastery evidence, assessment approaches, and misconception checks." primaryHref="/k12" primaryLabel="Explore K–12" secondaryHref="/docs/outcomes/aligning-assignments-to-standards" secondaryLabel="Alignment guide" /><main className="mx-auto max-w-[960px] px-5 py-14 md:px-10"><p className="max-w-3xl leading-relaxed">This launch covers a reviewed subset of NGSS middle-school performance expectations. Lextures links to official text and publishes an original summary rather than reproducing standards text. Filter through distinct framework and grade URLs so every selection works without client JavaScript.</p><h2 className="font-display mt-10 text-2xl font-semibold"><a href="/standards/ngss">Next Generation Science Standards</a></h2><ul className="mt-5 grid gap-4 md:grid-cols-2">{STANDARDS.map(item => <li key={item.code} className="rounded-[16px] border p-5" style={{ borderColor: 'var(--line-card)' }}><a href={`/standards/${item.framework}/${item.grade}/${item.code}`}>{item.code.toUpperCase()}: {item.summary}</a></li>)}</ul><UtilityLinks /></main></MarketingPageShell>
}

export function StandardsHubPage({ framework, grade }: { framework: string; grade?: string }) {
  const items = STANDARDS.filter(item => item.framework === framework && (!grade || item.grade === grade))
  return <MarketingPageShell><main className="mx-auto max-w-[900px] px-5 py-14 md:px-10"><a href="/standards">Standards browser</a><h1 className="font-display mt-8 text-4xl font-semibold">{items[0]?.frameworkName ?? framework}{grade ? ` — ${grade.replaceAll('-', ' ')}` : ''}</h1><p className="mt-4 max-w-3xl leading-relaxed">Browse original instructional guidance linked to the official source. NGSS trademarks and source materials belong to their respective owners; these pages do not imply endorsement.</p>{!grade && <p className="mt-6"><a href={`/standards/${framework}/middle-school`}>Browse middle-school science</a></p>}<ul className="mt-8 space-y-4">{items.map(item => <li key={item.code}><a href={`/standards/${item.framework}/${item.grade}/${item.code}`}>{item.code.toUpperCase()} — {item.subject}</a></li>)}</ul><UtilityLinks /></main></MarketingPageShell>
}

export function StandardPage({ framework, grade, code }: { framework: string; grade: string; code: string }) {
  const item = getStandard(framework, grade, code)
  if (!item) return null
  return <MarketingPageShell><main className="mx-auto max-w-[880px] px-5 py-14 md:px-10"><nav aria-label="Breadcrumb"><a href="/standards">Standards</a> / <a href={`/standards/${framework}`}>{item.frameworkName}</a> / <a href={`/standards/${framework}/${grade}`}>{grade.replaceAll('-', ' ')}</a></nav><h1 className="font-display mt-8 text-4xl font-semibold">{item.code.toUpperCase()}: assessment guidance</h1><p className="mt-3 text-lg leading-relaxed">{item.summary}</p><p className="mt-3 text-sm">Summary by Lextures. Read the <a href={item.source.href}>{item.source.label}</a> for official wording and dimensions.</p><section className="mt-10"><h2 className="font-display text-2xl font-semibold">What mastery looks like</h2><p className="mt-3 leading-relaxed">{item.mastery}</p></section><section className="mt-10"><h2 className="font-display text-2xl font-semibold">Assessment approaches</h2><ol className="mt-3 list-decimal space-y-3 pl-6">{item.approaches.map(value => <li key={value}>{value}</li>)}</ol></section><section className="mt-10"><h2 className="font-display text-2xl font-semibold">Common misconceptions</h2><ul className="mt-3 list-disc space-y-3 pl-6">{item.misconceptions.map(value => <li key={value}>{value}</li>)}</ul></section><p className="mt-8">Connect evidence to outcomes with <a href="/platform/analytics">Lextures learning analytics</a>, review <a href="/docs/outcomes/aligning-assignments-to-standards">standards alignment guidance</a>, or browse <a href="/courses">marketplace courses</a>.</p></main></MarketingPageShell>
}

export function TemplatesIndexPage() {
  return <MarketingPageShell><AudienceHero eyebrow="Ungated downloads" title="Teaching and course-design templates" lead="Preview and download practical, editable artifacts without creating an account." primaryHref="/tools" primaryLabel="Build online" secondaryHref="/docs" secondaryLabel="Read guidance" /><main className="mx-auto max-w-[960px] px-5 py-14 md:px-10"><ul className="grid gap-5 md:grid-cols-2">{TEMPLATES.map(item => <li key={item.slug} className="rounded-[18px] border p-6" style={{ borderColor: 'var(--line-card)', background: 'var(--panel)' }}><p className="text-sm">{item.audience}</p><h2 className="font-display mt-1 text-xl font-semibold"><a href={`/templates/${item.slug}`}>{item.title}</a></h2><p className="mt-2 leading-relaxed">{item.description}</p></li>)}</ul><UtilityLinks /></main></MarketingPageShell>
}

export function TemplatePage({ slug }: { slug: string }) {
  const item = getTemplate(slug); if (!item) return null
  return <MarketingPageShell><main className="mx-auto max-w-[880px] px-5 py-14 md:px-10"><a href="/templates">Templates</a><h1 className="font-display mt-8 text-4xl font-semibold">{item.title}</h1><p className="mt-4 text-lg leading-relaxed">{item.description}</p><section className="mt-9 rounded-[18px] border p-6" style={{ borderColor: 'var(--line-card)', background: 'var(--panel)' }}><h2 className="font-display text-2xl font-semibold">Preview</h2><ol className="mt-4 list-decimal space-y-2 pl-6">{item.preview.map(value => <li key={value}>{value}</li>)}</ol></section><section className="mt-9"><h2 className="font-display text-2xl font-semibold">Adapt this template</h2><p className="mt-3 leading-relaxed">{item.guidance}</p></section><div className="mt-8 flex flex-wrap gap-3"><a className="btn-primary" href={item.pdfHref} download>Download PDF</a><a className="btn-secondary" href={item.editableHref} download>Download editable DOCX</a><a className="btn-secondary" href={item.productHref}>Open in Lextures</a></div><section className="mt-9"><h2 className="font-display text-xl font-semibold">Source guidance</h2>{item.sources.map(source => <p className="mt-2" key={source.href}><a href={source.href}>{source.label}</a></p>)}</section><UtilityLinks /></main></MarketingPageShell>
}

export function ToolsIndexPage() {
  const tools = [['grade-calculator', 'Weighted grade calculator'], ['rubric-builder', 'Rubric builder'], ['reading-level', 'Reading-level checker'], ['assessment-blueprint', 'Assessment blueprint builder'], ['accessibility-checker', 'Accessibility checker']]
  return <MarketingPageShell><AudienceHero eyebrow="Private by design" title="Free teaching tools" lead="Calculate, draft, check, and share in your browser. Sensitive text stays on your device." primaryHref="/tools/grade-calculator" primaryLabel="Calculate a grade" secondaryHref="/templates" secondaryLabel="Browse templates" /><main className="mx-auto max-w-[960px] px-5 py-14 md:px-10"><ul className="grid gap-4 md:grid-cols-2">{tools.map(([slug, title]) => <li key={slug} className="rounded-[16px] border p-5" style={{ borderColor: 'var(--line-card)' }}><h2 className="font-display text-xl font-semibold"><a href={`/tools/${slug}`}>{title}</a></h2></li>)}</ul><UtilityLinks /></main></MarketingPageShell>
}

export function ToolPage({ tool }: { tool: string }) {
  const [input, setInput] = useState(() => typeof window === 'undefined' ? '' : new URLSearchParams(window.location.search).get('v') ?? '')
  const [notice, setNotice] = useState('')
  const result = useMemo(() => {
    if (tool === 'grade-calculator') { const values = input.split(',').map(Number).filter(Number.isFinite); return values.length ? `${(values.reduce((a, b) => a + b, 0) / values.length).toFixed(1)}% average` : 'Enter comma-separated percentages.' }
    if (tool === 'reading-level') { const words = input.trim().split(/\s+/).filter(Boolean); const sentences = input.split(/[.!?]+/).filter(value => value.trim()).length || 1; return words.length ? `${words.length} words; ${sentences} sentences; ${(words.length / sentences).toFixed(1)} words per sentence.` : 'Paste text to inspect its sentence length.' }
    if (tool === 'accessibility-checker') { const issues = [!/^\s*#{1,6}\s/m.test(input) && 'Add a heading.', /click here/i.test(input) && 'Replace “click here” with a descriptive link label.'].filter(Boolean); return issues.length ? issues.join(' ') : input ? 'No basic text-pattern issues found; manual WCAG review is still required.' : 'Paste a Markdown course-page snippet.' }
    return input ? `Draft ready: ${input}` : 'Describe the criteria or objectives you need.'
  }, [input, tool])
  const names: Record<string, string> = { 'grade-calculator': 'Weighted grade calculator', 'rubric-builder': 'Rubric builder', 'reading-level': 'Reading-level checker', 'assessment-blueprint': 'Assessment blueprint builder', 'accessibility-checker': 'Accessibility checker' }
  const share = async () => { const url = new URL(window.location.href); url.searchParams.set('v', input); history.replaceState({}, '', url); await navigator.clipboard?.writeText(url.toString()); setNotice('Share URL copied.') }
  return <MarketingPageShell><main className="mx-auto max-w-[880px] px-5 py-14 md:px-10"><a href="/tools">All tools</a><h1 className="font-display mt-8 text-4xl font-semibold">{names[tool] ?? 'Teaching tool'}</h1><p className="mt-4 max-w-3xl text-lg leading-relaxed">Use this free tool without an account. Its instructions and explanation are available in the static page, while calculations run only after JavaScript loads. Your entries stay in this browser and are never sent to Lextures or a third party.</p><section className="mt-9 rounded-[18px] border p-6" style={{ borderColor: 'var(--line-card)', background: 'var(--panel)' }}><label htmlFor="tool-input" className="font-semibold">{tool === 'grade-calculator' ? 'Percentages, separated by commas' : 'Working text'}</label><textarea id="tool-input" className="mt-3 min-h-36 w-full rounded-lg border p-3" value={input} onChange={event => setInput(event.target.value)} aria-describedby="privacy-note" /><p id="privacy-note" className="mt-2 text-sm">Processed locally. The share action places this input in the URL only when you choose it.</p><h2 className="font-display mt-6 text-xl font-semibold">Result</h2><p className="mt-2" role="status" aria-live="polite">{result}</p><button type="button" className="btn-secondary mt-5" onClick={share}>Copy share URL</button><p role="status" aria-live="polite" className="mt-2 text-sm">{notice}</p></section><section className="mt-10"><h2 className="font-display text-2xl font-semibold">How to use the result</h2><p className="mt-3 leading-relaxed">Treat the output as a starting point for professional review. Check the underlying learning objective, inspect outliers, and document the decision you make from the result. A calculator or heuristic can make a pattern visible, but it cannot determine instructional quality, accessibility conformance, or fairness on its own. Verify important choices with the original scoring policy, learning goals, and representative learner work. When checking accessibility, automated patterns cover only a small part of conformance; keyboard, zoom, semantics, and assistive-technology testing remain essential. Save or share only information you are permitted to place in a URL.</p><p className="mt-3">Method references: <a href="https://www.w3.org/TR/WCAG22/">W3C WCAG 2.2</a> and <a href="https://nces.ed.gov/nceskids/help/user_guide/graph/whentouse.asp">NCES guidance on selecting representations</a>.</p></section><UtilityLinks /></main></MarketingPageShell>
}
