output "region" {
  description = "OCI region."
  value       = var.region
}

output "availability_domain" {
  description = "Availability domain hosting the instance and data volume."
  value       = local.availability_domain
}

output "instance_id" {
  description = "Compute instance OCID."
  value       = oci_core_instance.app.id
}

output "instance_shape" {
  description = "Compute shape slug."
  value       = var.instance_shape
}

output "reserved_ipv4" {
  description = "Reserved public IPv4 — use for DNS A records and VITE_API_URL."
  value       = oci_core_public_ip.app.ip_address
}

output "data_volume_id" {
  description = "Block volume OCID for PostgreSQL and course files."
  value       = oci_core_volume.data.id
}

output "postgres_data_mount" {
  description = "Host path for Postgres data (bind mount from block volume)."
  value       = "/mnt/lextures-db/postgres"
}

output "course_files_mount" {
  description = "Host path for uploaded course files."
  value       = "/mnt/lextures-db/course-files"
}

output "ssh_root" {
  description = "Example SSH command as ubuntu via the reserved IP."
  value       = "ssh -i <private-key-file> ubuntu@${oci_core_public_ip.app.ip_address}"
}

output "ssh_private_key_openssh" {
  description = "OpenSSH private key for the instance (generated by Terraform; use with ssh -i)."
  value       = tls_private_key.app.private_key_openssh
  sensitive   = true
}

output "ssh_public_key_openssh" {
  description = "OpenSSH public key installed on the instance."
  value       = tls_private_key.app.public_key_openssh
}

output "deploy_compose_command" {
  description = "Restart the app stack after changing images (requires /opt/lextures/.env from cloud-init)."
  value       = "sudo /usr/local/bin/lextures-deploy-app.sh"
}

output "bootstrap_log_path" {
  description = "Cloud-init bootstrap log on the VM."
  value       = "/var/log/lextures-bootstrap.log"
}

output "deploy_postgres_password" {
  description = "Postgres password written to /opt/lextures/.env when deploy_enabled is true."
  value       = var.deploy_enabled ? local.deploy_postgres_password : null
  sensitive   = true
}

output "deploy_jwt_secret" {
  description = "JWT secret written to /opt/lextures/.env when deploy_enabled is true."
  value       = var.deploy_enabled ? local.deploy_jwt_secret : null
  sensitive   = true
}

output "deploy_public_origin" {
  description = "PUBLIC_WEB_ORIGIN configured for the API (empty means cloud-init auto-detects http://<public-ip>)."
  value       = var.deploy_public_origin
}

output "estimated_monthly_cost_usd" {
  description = "Rough cost estimate when within Always Free limits (USD/mo; excludes egress)."
  value       = "$0 within Always Free (2 OCPU A1 + 150 GB block storage); paid overage varies by region"
}
