import type { ReactNode } from 'react'
import { AnswerBox, ComparisonTable, FAQ } from './content'
import { MarketingPageShell, AudienceHero } from './marketing-page-shell'
import type { Competitor } from '../lib/competitors'
import type { Integration } from '../lib/integrations'
import { COMPARISON_CRITERIA } from '../lib/comparison-criteria'

const verifiedLabel = 'August 11, 2026'

export function PublisherDisclosure() {
  return <aside className="comparison-disclosure"><strong>Publisher disclosure.</strong> This comparison is published by Lextures. We’ve documented where each product is stronger and cited capability claims to the vendor’s own documentation. Last verified {verifiedLabel}.</aside>
}

export function VerifiedBadge() { return <p className="comparison-verified">Last verified <time dateTime="2026-08-11">{verifiedLabel}</time> · Quarterly review required</p> }

export function ComparisonMatrix({ competitor }: { competitor: Competitor }) {
  const values: Record<(typeof COMPARISON_CRITERIA)[number], [string, string]> = {
    'Adaptive delivery': ['IRT-routed quizzes and spaced review', 'See vendor documentation'],
    'Question bank and quizzes': ['Reusable question banks and interactive quizzes', 'See vendor documentation'],
    'Rubrics and peer review': ['Rubrics and peer-review workflows', 'See vendor documentation'],
    'Gradebook and audit trail': ['Unified grading with recorded changes', 'See vendor documentation'],
    'Standards and outcomes': ['Course outcomes and standards alignment', 'See vendor documentation'],
    'SIS roster sync': ['Deployment-specific roster exchange', 'See vendor documentation'],
    'LTI support': ['LTI 1.3; enabled Advantage services vary', 'See vendor documentation'],
    'SSO and provisioning': ['SAML 2.0, OIDC, and SCIM 2.0 where enabled', 'See vendor documentation'],
    'Accessibility documentation': ['Public accessibility statement and VPAT', 'See vendor documentation'],
    'Self-hosting': ['Hosted service or AGPL-3.0 self-hosting', competitor.slug === 'moodle' || competitor.slug === 'open-edx' ? 'Self-managed options documented' : 'See vendor deployment options'],
    'Data export and API': ['Institution export, API, and signed webhooks where enabled', 'See vendor documentation'],
    'Pricing transparency': ['Published institution tiers and self-host license option', competitor.pricingPublic ? 'Public pricing available' : 'Pricing is not published; request a quote'],
  }
  const rows = COMPARISON_CRITERIA.map(criterion => [criterion, ...values[criterion]])
  return <ComparisonTable summary={`Lextures emphasizes adaptive practice and deployment ownership; ${competitor.name} is strongest for teams seeking ${competitor.summary}.`}>
    <table><caption>Lextures and {competitor.name} capability summary, as of {verifiedLabel}</caption><thead><tr><th scope="col">Criterion</th><th scope="col">Lextures</th><th scope="col">{competitor.name}</th></tr></thead><tbody>{rows.map(([criterion, lextures, other]) => <tr key={criterion}><th scope="row">{criterion}</th><td>{lextures}</td><td>{other} <a href={competitor.docsUrl} rel="noopener noreferrer">Vendor documentation (accessed 2026-08-11)</a></td></tr>)}</tbody></table>
  </ComparisonTable>
}

export function MigrationPath({ competitor }: { competitor: Competitor }) { return <section><h2>Migration path</h2><p>Start with a representative course export and inventory content, users, enrollments, assessments, outcomes, grades, and integrations. What carries over depends on the export that {competitor.name} produces and the enabled Lextures import paths. Custom tools, app-specific settings, analytics history, and some question types may require reconstruction. Validate a pilot course before estimating schedule or cost.</p></section> }

export function ComparisonArticle({ competitor }: { competitor: Competitor }) {
  const faqs = [
    { question: `Is Lextures better than ${competitor.name}?`, answer: `Neither is universally better. Lextures fits teams prioritizing adaptive practice, self-hosting, and transparent deployment choices; ${competitor.name} may fit teams that value ${competitor.summary}.` },
    { question: `Can we migrate from ${competitor.name}?`, answer: 'A staged migration is possible, but portability depends on the source export. Test one representative course before committing to cost or timing.' },
    { question: 'Does Lextures support LTI 1.3?', answer: 'Lextures supports LTI 1.3 deployments. Available LTI Advantage services depend on configuration and should be verified in a pilot.' },
    { question: 'Can Lextures be self-hosted?', answer: 'Yes. Lextures is available under AGPL-3.0 for self-hosting; operating infrastructure and support remain the deployer’s responsibility.' },
  ]
  return <MarketingPageShell><AudienceHero eyebrow="Product comparison" title={`Lextures vs. ${competitor.name}`} lead={`A factual evaluation for ${competitor.segment} teams comparing ownership, adaptive learning, interoperability, and implementation.`} primaryHref="/request-information" primaryLabel="Request information" secondaryHref="/pricing" secondaryLabel="See pricing" />
    <article className="comparison-article"><AnswerBox>Choose Lextures when adaptive practice, open-source self-hosting, and direct control over integrations matter most. Choose {competitor.name} when your priority is {competitor.summary}. Validate both against your roster, identity, accessibility, migration, and support requirements before signing a contract.</AnswerBox>
      <PublisherDisclosure/><VerifiedBadge/><ComparisonMatrix competitor={competitor}/>
      <section><h2>Where {competitor.name} is stronger</h2><ul>{competitor.strengths.map(x => <li key={x}>{x}. <a href={competitor.docsUrl} rel="noopener noreferrer">Vendor documentation (accessed 2026-08-11)</a></li>)}</ul></section>
      <section><h2>Where Lextures is stronger</h2><ul><li>Adaptive quiz routing and spaced review are core platform workflows; see <a href="/platform/adaptive-learning">adaptive learning</a>.</li><li>AGPL-3.0 self-hosting provides deployment control; see the <a href="/docs/self-hosting/self-hosting">self-hosting guide</a>.</li><li>Implementation teams can review <a href="/security">security practices</a> and the public <a href="/accessibility/vpat">VPAT</a>.</li></ul></section>
      <MigrationPath competitor={competitor}/><section><h2>Pricing comparison</h2><p>Lextures publishes its current options on the <a href="/pricing">pricing page</a>. {competitor.pricingPublic ? <>The vendor publishes pricing or edition information on its <a href={competitor.pricingUrl} rel="noopener noreferrer">pricing page (accessed 2026-08-11)</a>; compare scope and services, not just headline price.</> : <>{competitor.name} does not publish a complete price list. Request a written quote and do not rely on third-party estimates.</>}</p></section>
      <FAQ items={faqs}/><PolicyFooter/></article><BottomCta href="/request-information">Evaluate Lextures with your requirements</BottomCta></MarketingPageShell>
}

export function AlternativesArticle({ competitor, options }: { competitor: Competitor; options: Competitor[] }) {
  const ranked = [competitor, ...options.filter(x => x.slug !== competitor.slug).slice(0, 7)]
  return <MarketingPageShell><AudienceHero eyebrow="LMS alternatives" title={`8 alternatives to ${competitor.name}`} lead="A criteria-led shortlist covering institutional LMSs, open-source platforms, and focused teaching tools." primaryHref="/request-information" primaryLabel="Request information" secondaryHref="/compare" secondaryLabel="Compare Lextures" />
    <article className="comparison-article"><AnswerBox>The best alternative depends on whether you need a full institutional LMS, open-source control, creator commerce, or a lightweight classroom workflow. Use interoperability, accessibility evidence, migration effort, hosting model, and total cost as screening criteria before ranking any vendor.</AnswerBox><PublisherDisclosure/><VerifiedBadge/>
      <section><h2>How these alternatives were evaluated</h2><p>We assessed audience fit, adaptive learning, assessment depth, identity and roster options, accessibility documentation, deployment control, migration effort, and pricing transparency. Unknown capabilities are not treated as absent.</p></section>
      <ComparisonTable summary={`${competitor.name} remains in the list so readers can compare the incumbent under the same criteria as every alternative.`}><table><caption>Alternatives to {competitor.name}, verified {verifiedLabel}</caption><thead><tr><th scope="col">Option</th><th scope="col">Best fit</th><th scope="col">Evidence</th></tr></thead><tbody>{ranked.map((item, index) => <tr key={item.slug}><th scope="row">{index + 1}. {item.name}</th><td>{item.summary}</td><td><a href={item.docsUrl} rel="noopener noreferrer">Vendor documentation (accessed 2026-08-11)</a>{item.slug !== competitor.slug && <> · <a href={`/compare/lextures-vs-${item.slug}`}>Lextures comparison</a></>}</td></tr>)}</tbody></table></ComparisonTable>
      <section><h2>When Lextures belongs on the shortlist</h2><p>Consider Lextures when adaptive practice, transparent <a href="/pricing">pricing</a>, and <a href="/docs/self-hosting/self-hosting">self-hosting</a> are material requirements. Review the <a href="/platform">platform capabilities</a> and test a representative migration before selecting it.</p></section>
      <FAQ items={[{question:`What is the best ${competitor.name} alternative?`,answer:'There is no universal best option. Start with audience, hosting, interoperability, accessibility, migration, and budget requirements, then test the finalists.'},{question:`Is ${competitor.name} still included?`,answer:'Yes. The incumbent is evaluated under the same criteria because keeping it may be the lowest-risk option.'},{question:'Are unknown features treated as missing?',answer:'No. A capability that could not be verified is treated as not publicly documented, not as unsupported.'},{question:'Should we run a pilot?',answer:'Yes. Use representative courses, identities, assessments, grades, and integrations before a contract decision.'}]}/><PolicyFooter/></article><BottomCta href="/request-information">Build an institution-ready shortlist</BottomCta></MarketingPageShell>
}

export function IntegrationArticle({ integration }: { integration: Integration }) { return <MarketingPageShell><AudienceHero eyebrow="Integration guide" title={`Lextures and ${integration.name}`} lead={integration.capability} primaryHref={integration.helpPath} primaryLabel="Open setup guide" secondaryHref="/request-information" secondaryLabel="Discuss your environment"/><article className="comparison-article"><AnswerBox>{integration.native ? `Lextures supports ${integration.name} with the versions and boundaries below.` : `Lextures does not currently document a turnkey native ${integration.name} connector.`} Plan a limited pilot and verify identity, permissions, data fields, failure handling, and rollback before production use.</AnswerBox><VerifiedBadge/><IntegrationSpec integration={integration}/><section><h2>Setup steps</h2><ol><li>Confirm that the stated capability and version meet your requirement.</li><li>Assign an administrator and test with synthetic or limited data.</li><li>Configure credentials with minimum permissions and record ownership.</li><li>Verify successful and failed exchanges at both systems.</li><li>Document monitoring, support, rollback, and the production cutover.</li></ol><p>Follow the <a href={integration.helpPath}>corresponding Lextures help article</a>. Also review <a href="/security">security practices</a> and <a href="/docs/integrations/using-webhooks">webhook operations</a>.</p></section><FAQ items={[{question:`Is ${integration.name} a native Lextures integration?`,answer:integration.native?'Yes, within the documented versions and enabled platform features. Confirm the exact deployment in a pilot.':'No turnkey native connector is currently documented. Contact Lextures before planning a custom implementation.'},{question:'How long does setup take?',answer:`Expected effort: ${integration.effort}. Timing depends on approvals, data mapping, testing, and the connected system.`},{question:'Should we test with production learner data?',answer:'No. Begin with synthetic or tightly limited data and expand only after permissions, mapping, errors, and rollback have been verified.'},{question:'Where are setup instructions?',answer:`The linked Lextures help article describes the closest supported setup path and operational checks.`}]}/></article><BottomCta href="/request-information">Validate this integration with Lextures</BottomCta></MarketingPageShell> }

export function IntegrationSpec({ integration }: { integration: Integration }) { return <section><h2>Supported specification</h2><dl className="integration-spec"><div><dt>Status</dt><dd>{integration.native ? 'Supported when enabled' : 'No turnkey native connector documented'}</dd></div><div><dt>Version or protocol</dt><dd>{integration.version}</dd></div><div><dt>Capabilities</dt><dd>{integration.capability}</dd></div><div><dt>Setup effort</dt><dd>{integration.effort}</dd></div></dl></section> }
function PolicyFooter(){ return <footer className="comparison-policy"><h2>Disclosure, trademarks, and corrections</h2><p>Competitor names are used nominatively to identify the products discussed. No competitor logo, wordmark, or trade dress is used. Lextures publishes this page and has no affiliation with the named vendor.</p><p>Report an inaccuracy to <a href="mailto:corrections@lextures.com">corrections@lextures.com</a>. We acknowledge requests within two business days and resolve or answer them within five. Changelog: 2026-08-11 — initial publication.</p></footer> }
function BottomCta({href,children}:{href:string;children:ReactNode}){ return <section className="comparison-cta"><h2>{children}</h2><p>Review <a href="/pricing">pricing</a>, explore the <a href="/higher-ed">higher-education</a> and <a href="/k12">K–12</a> paths, or bring your requirements to our team.</p><a className="btn-primary" href={href} data-seo-cta="comparison">Request information</a></section> }
