output "region" {
  description = "DigitalOcean region slug."
  value       = var.region
}

output "droplet_id" {
  description = "DigitalOcean droplet ID."
  value       = digitalocean_droplet.app.id
}

output "droplet_size" {
  description = "Droplet size slug."
  value       = var.droplet_size
}

output "reserved_ipv4" {
  description = "Reserved (floating) IPv4 — use for DNS A records and VITE_API_URL."
  value       = digitalocean_reserved_ip.app.ip_address
}

output "droplet_ipv4" {
  description = "Ephemeral public IPv4 on the droplet NIC (prefer reserved_ipv4 for DNS)."
  value       = digitalocean_droplet.app.ipv4_address
}

output "data_volume_id" {
  description = "Block volume ID for PostgreSQL and course files."
  value       = digitalocean_volume.data.id
}

output "postgres_data_mount" {
  description = "Host path for Postgres data (bind mount from block volume)."
  value       = "/mnt/lextures-db/postgres"
}

output "course_files_mount" {
  description = "Host path for uploaded course files."
  value       = "/mnt/lextures-db/course-files"
}

output "ssh_root" {
  description = "Example SSH command as root via the reserved IP."
  value       = "ssh -i <private-key-file> root@${digitalocean_reserved_ip.app.ip_address}"
}

output "ssh_private_key_openssh" {
  description = "OpenSSH private key for root (generated by Terraform; use with ssh -i)."
  value       = tls_private_key.app.private_key_openssh
  sensitive   = true
}

output "ssh_public_key_openssh" {
  description = "OpenSSH public key registered on the droplet."
  value       = tls_private_key.app.public_key_openssh
}

output "deploy_compose_command" {
  description = "Example command to restart the stack after changing images or .env."
  value       = "/usr/local/bin/lextures-deploy-app.sh"
}

output "deploy_postgres_password" {
  description = "Postgres password written to /opt/lextures/.env when deploy_enabled is true."
  value       = var.deploy_enabled ? local.deploy_postgres_password : null
  sensitive   = true
}

output "deploy_jwt_secret" {
  description = "JWT secret written to /opt/lextures/.env when deploy_enabled is true."
  value       = var.deploy_enabled ? local.deploy_jwt_secret : null
  sensitive   = true
}

output "deploy_public_origin" {
  description = "PUBLIC_WEB_ORIGIN configured for the API (empty means cloud-init auto-detects http://<public-ip>)."
  value       = var.deploy_public_origin
}

output "estimated_monthly_cost_usd" {
  description = "Rough list-price estimate (USD/mo, excludes egress and image registry)."
  value       = "~57 (s-4vcpu-8gb + 50 GB volume + reserved IP; add ~20% for optional droplet backups)"
}
