package com.lextures.android.features.reading

import androidx.compose.runtime.Composable
import com.lextures.android.R
import com.lextures.android.core.i18n.L

@Composable fun readingTitle(): String = L.text(R.string.mobile_reading_title)
@Composable fun readingLogAction(): String = L.text(R.string.mobile_reading_logAction)
@Composable fun readingWeeklyPages(): String = L.text(R.string.mobile_reading_weeklyPages)
@Composable fun readingReadingStreak(): String = L.text(R.string.mobile_reading_readingStreak)
@Composable fun readingLoginStreak(): String = L.text(R.string.mobile_reading_loginStreak)
@Composable fun readingStreakDays(count: Int): String = L.plural(R.plurals.mobile_reading_streakDays, count)
@Composable fun readingLibraryTitle(): String = L.text(R.string.mobile_reading_libraryTitle)
@Composable fun readingLibraryHint(): String = L.text(R.string.mobile_reading_libraryHint)
@Composable fun readingBookClubTitle(): String = L.text(R.string.mobile_reading_bookClubTitle)
@Composable fun readingBookClubHint(): String = L.text(R.string.mobile_reading_bookClubHint)
@Composable fun readingBookClubEmpty(): String = L.text(R.string.mobile_reading_bookClubEmpty)
@Composable fun readingHistoryTitle(): String = L.text(R.string.mobile_reading_historyTitle)
@Composable fun readingHistoryEmptyTitle(): String = L.text(R.string.mobile_reading_historyEmptyTitle)
@Composable fun readingHistoryEmptyMessage(): String = L.text(R.string.mobile_reading_historyEmptyMessage)
@Composable fun readingUnknownBook(): String = L.text(R.string.mobile_reading_unknownBook)
@Composable fun readingPagesCount(pages: Int): String = L.format(R.string.mobile_reading_pagesCount, pages)
@Composable fun readingLogTitle(): String = L.text(R.string.mobile_reading_logTitle)
@Composable fun readingLogBookTitle(): String = L.text(R.string.mobile_reading_logBookTitle)
@Composable fun readingLogBookPlaceholder(): String = L.text(R.string.mobile_reading_logBookPlaceholder)
@Composable fun readingLogDate(): String = L.text(R.string.mobile_reading_logDate)
@Composable fun readingLogPages(): String = L.text(R.string.mobile_reading_logPages)
@Composable fun readingLogPagesPlaceholder(): String = L.text(R.string.mobile_reading_logPagesPlaceholder)
@Composable fun readingLogReflection(): String = L.text(R.string.mobile_reading_logReflection)
@Composable fun readingLogReflectionPlaceholder(): String = L.text(R.string.mobile_reading_logReflectionPlaceholder)
@Composable fun readingLogSave(): String = L.text(R.string.mobile_reading_logSave)
@Composable fun readingSaving(): String = L.text(R.string.mobile_reading_saving)
@Composable fun readingAllLevels(): String = L.text(R.string.mobile_reading_allLevels)
@Composable fun readingLibraryEmptyTitle(): String = L.text(R.string.mobile_reading_libraryEmptyTitle)
@Composable fun readingLibraryEmptyMessage(): String = L.text(R.string.mobile_reading_libraryEmptyMessage)
@Composable fun readingLogThisBook(): String = L.text(R.string.mobile_reading_logThisBook)
@Composable fun readingPreviewOpen(): String = L.text(R.string.mobile_reading_previewOpen)
@Composable fun readingPreviewTitle(): String = L.text(R.string.mobile_reading_previewTitle)
@Composable fun readingErrorLoad(): String = L.text(R.string.mobile_reading_error_load)
@Composable fun readingErrorSave(): String = L.text(R.string.mobile_reading_error_save)
@Composable fun readingErrorValidation(): String = L.text(R.string.mobile_reading_error_validation)
@Composable fun readingDisabledTitle(): String = L.text(R.string.mobile_reading_disabledTitle)
@Composable fun readingDisabledMessage(): String = L.text(R.string.mobile_reading_disabledMessage)