import {
  OutputNode,
  GraderNode,
  CriterionGraderNode,
  AiNode,
  ActivityNode,
  StudentSubmissionNode,
  SubmissionNode,
  QuizResponsesNode,
  AssignmentContextNode,
  CodeTestRunnerNode,
  ConditionalRouterNode,
  FlagForReviewNode,
  HumanReviewGateNode,
  OriginalityNode,
  ReferenceNode,
  RubricNode,
  ScoreAggregatorNode,
  SetScoreNode,
  GroupNode,
} from './workflow-nodes'

export const graderAgentNodeTypes = {
  output: OutputNode,
  grader: GraderNode,
  criterionGrader: CriterionGraderNode,
  ai: AiNode,
  activity: ActivityNode,
  studentSubmission: StudentSubmissionNode,
  quizResponses: QuizResponsesNode,
  submission: SubmissionNode,
  assignmentContext: AssignmentContextNode,
  codeTestRunner: CodeTestRunnerNode,
  conditionalRouter: ConditionalRouterNode,
  flagForReview: FlagForReviewNode,
  humanReviewGate: HumanReviewGateNode,
  originality: OriginalityNode,
  reference: ReferenceNode,
  rubric: RubricNode,
  scoreAggregator: ScoreAggregatorNode,
  setScore: SetScoreNode,
  group: GroupNode,
}
