import {
  OutputNode,
  GraderNode,
  CriterionGraderNode,
  AiNode,
  ActivityNode,
  StudentSubmissionNode,
  SubmissionNode,
  AssignmentContextNode,
  CodeTestRunnerNode,
  ConditionalRouterNode,
  FlagForReviewNode,
  HumanReviewGateNode,
  OriginalityNode,
} from './workflow-nodes'

export const graderAgentNodeTypes = {
  output: OutputNode,
  grader: GraderNode,
  criterionGrader: CriterionGraderNode,
  ai: AiNode,
  activity: ActivityNode,
  studentSubmission: StudentSubmissionNode,
  submission: SubmissionNode,
  assignmentContext: AssignmentContextNode,
  codeTestRunner: CodeTestRunnerNode,
  conditionalRouter: ConditionalRouterNode,
  flagForReview: FlagForReviewNode,
  humanReviewGate: HumanReviewGateNode,
  originality: OriginalityNode,
}
