import XCTest
@testable import Lextures

final class VibeActivityLogicTests: XCTestCase {
    func testParseHeadingAndParagraph() {
        let html = """
        <!doctype html><html><body>
        <h1 data-testid="vibe-heading">Seeded Vibe Activity</h1>
        <p>This content was generated by the test.</p>
        </body></html>
        """
        let doc = VibeActivityLogic.parse(html: html)
        XCTAssertFalse(doc.requiresWebFallback)
        XCTAssertTrue(doc.blocks.contains {
            if case .heading(let level, let text) = $0.kind {
                return level == 1 && text.contains("Seeded Vibe Activity")
            }
            return false
        })
        XCTAssertTrue(doc.blocks.contains {
            if case .paragraph(let text) = $0.kind {
                return text.contains("generated by the test")
            }
            return false
        })
    }

    func testParseDetailsReveal() {
        let html = """
        <body><details><summary>Show answer</summary><p>The answer is 42.</p></details></body>
        """
        let doc = VibeActivityLogic.parse(html: html)
        XCTAssertTrue(doc.blocks.contains {
            if case .reveal(let trigger, let body) = $0.kind {
                return trigger == "Show answer" && body.contains("42")
            }
            return false
        })
    }

    func testParseUnsupportedIframeOnly() {
        let html = "<body><iframe src=\"https://example.com\"></iframe></body>"
        let doc = VibeActivityLogic.parse(html: html)
        XCTAssertTrue(doc.requiresWebFallback)
        XCTAssertTrue(doc.blocks.contains {
            if case .unsupported = $0.kind { return true }
            return false
        })
    }

    func testEmptyHtmlFallback() {
        let doc = VibeActivityLogic.parse(html: "  ")
        XCTAssertFalse(doc.requiresWebFallback)
        XCTAssertEqual(doc.blocks.count, 1)
        if case .paragraph(let text) = doc.blocks[0].kind {
            XCTAssertTrue(text.contains("Empty activity"))
        } else {
            XCTFail("Expected empty-state paragraph")
        }
    }

    func testWebPath() {
        let path = VibeActivityLogic.webPath(courseCode: "CS 101", itemId: "item-1")
        XCTAssertTrue(path.contains("/courses/"))
        XCTAssertTrue(path.contains("vibe-activity"))
    }
}