package com.lextures.android.core.lms

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class VibeActivityLogicTest {
    @Test
    fun parseHeadingAndParagraph() {
        val html = """
            <!doctype html><html><body>
            <h1 data-testid="vibe-heading">Seeded Vibe Activity</h1>
            <p>This content was generated by the test.</p>
            </body></html>
        """.trimIndent()
        val doc = VibeActivityLogic.parse(html)
        assertFalse(doc.requiresWebFallback)
        assertTrue(
            doc.blocks.any {
                it.kind is VibeActivityBlockKind.Heading &&
                    (it.kind as VibeActivityBlockKind.Heading).text.contains("Seeded Vibe Activity")
            },
        )
        assertTrue(
            doc.blocks.any {
                it.kind is VibeActivityBlockKind.Paragraph &&
                    (it.kind as VibeActivityBlockKind.Paragraph).text.contains("generated by the test")
            },
        )
    }

    @Test
    fun parseDetailsReveal() {
        val html = """<body><details><summary>Show answer</summary><p>The answer is 42.</p></details></body>"""
        val doc = VibeActivityLogic.parse(html)
        assertTrue(
            doc.blocks.any {
                it.kind is VibeActivityBlockKind.Reveal &&
                    (it.kind as VibeActivityBlockKind.Reveal).trigger == "Show answer" &&
                    (it.kind as VibeActivityBlockKind.Reveal).body.contains("42")
            },
        )
    }

    @Test
    fun parseUnsupportedIframeOnly() {
        val html = """<body><iframe src="https://example.com"></iframe></body>"""
        val doc = VibeActivityLogic.parse(html)
        assertTrue(doc.requiresWebFallback)
        assertTrue(doc.blocks.any { it.kind is VibeActivityBlockKind.Unsupported })
    }

    @Test
    fun emptyHtmlFallback() {
        val doc = VibeActivityLogic.parse("   ")
        assertFalse(doc.requiresWebFallback)
        assertEquals(1, doc.blocks.size)
        assertTrue((doc.blocks.first().kind as VibeActivityBlockKind.Paragraph).text.contains("Empty activity"))
    }

    @Test
    fun webPathIncludesCourseAndItem() {
        val path = VibeActivityLogic.webPath("CS 101", "item-1")
        assertTrue(path.contains("/courses/"))
        assertTrue(path.contains("vibe-activity"))
    }
}