import Foundation

// MARK: - Platform features

/// GET `/api/v1/platform/features` (subset used on mobile).
struct PlatformFeatures: Decodable {
    var ffWhatifGrades: Bool?
    var feedbackMediaEnabled: Bool?
    var ffLibrary: Bool?
    var ffCourseEvaluations: Bool?
    var ffMobileCourseEvaluations: Bool?
    var ffMobileIaRedesign: Bool?
    var ffMobileVibeActivities: Bool?
    var ffMobileUniversalSearch: Bool?
    var ffMobileProfileDepth: Bool?
    var ffMobileLibraryEreserves: Bool?
    var ffMobileImmersiveReader: Bool?
    var ffMobileLiveMeetings: Bool?
    var readAloudEnabled: Bool?
    var ffReadAloud: Bool?
    var videoCaptionsEnabled: Bool?
    var autoCaptioningEnabled: Bool?
    var translationMemoryEnabled: Bool?
    var ffReadingPreferences: Bool?
    var ffMotionNavigation: Bool?
    var ffMotionReveal: Bool?
    var ffMotionLists: Bool?
    var oerLibraryEnabled: Bool?
    var xapiEmissionEnabled: Bool?
    var customFieldsEnabled: Bool?
    var ffDemographics: Bool?
    var ffResearchConsent: Bool?
    var ffPersistentTutor: Bool?
    var ffAiStudyBuddy: Bool?
    var ragNotebookEnabled: Bool?
    var aiStudyBuddyEnabled: Bool?
    var aiDisclosureEnabled: Bool?
    var ffPeerReview: Bool?
    var ffLearningPaths: Bool?
    var selfReflectionEnabled: Bool?
    var ffPublicCatalog: Bool?
    var ffCourseMarketplace: Bool?
    var ffSelfPacedMode: Bool?
    var ffCourseReviews: Bool?
    var ffCompletionCredentials: Bool?
    var ffCoCurricularTranscript: Bool?
    var ffTranscripts: Bool?
    var ffCeuTracking: Bool?
    var ffEportfolio: Bool?
    var ffGamification: Bool?
    var ffStripeBilling: Bool?
    var ffPaymentsEnabled: Bool?
    var ffTaxCollection: Bool?
    var ffAdvisingIntegration: Bool?
    var ffMobileAdvising: Bool?
    var ffParentPortal: Bool?
    var ffConferenceScheduling: Bool?
    var ffClassroomSignals: Bool?
    var ffBroadcasts: Bool?
    var ffUiMode: Bool?
    var atRiskAlertsEnabled: Bool?
    var instructorInsightsEnabled: Bool?
    var studentProgressEnabled: Bool?
    var ffMobileInstructorInsights: Bool?
    var ffMobileCourseSettings: Bool?
    var ffMobileCreateCourse: Bool?
    var ffMobileCourseCreateV2: Bool?
    var ffMobileCanvasImport: Bool?
    var ffMobileAdminConsole: Bool?
    var ffMobileEnrollmentAdd: Bool?
    var ffMobileLiveQuiz: Bool?
    var ffMobileWhiteboardEdit: Bool?
    var ffEnrollmentStateMachine: Bool?
    var adminConsoleEnabled: Bool?
    var adminAuditLogEnabled: Bool?
    var ffConsortiumSharing: Bool?
    var graderAgentEnabled: Bool?
    var ffPlagiarismChecks: Bool?
    var altTextEnforcementEnabled: Bool?
    var learnerProfileEnabled: Bool?
    var ffMobileLearnerProfile: Bool?
    var introCourseEnabled: Bool?
    var ffApiTokens: Bool?
    var ffCalendarFeeds: Bool?
    var ffMobileSettingsIntegrations: Bool?
    var ffMobileAdminSettings: Bool?
    var ffFeedback: Bool?
}