-- Platform feature flags and gates (managed in Settings → Global platform; not process env).
ALTER TABLE settings.platform_app_settings
    ADD COLUMN IF NOT EXISTS oidc_sso_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS clever_sso_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS classlink_sso_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS magic_link_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS magic_link_enrolled_only BOOLEAN,
    ADD COLUMN IF NOT EXISTS session_management_ui_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS email_notifications_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS push_notifications_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS virtual_classroom_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS drm_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS video_transcoding_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS auto_captioning_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS storage_quotas_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS at_risk_alerts_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS av_scanning_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS clamav_stub BOOLEAN,
    ADD COLUMN IF NOT EXISTS h5p_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS oer_library_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS oer_stub BOOLEAN,
    ADD COLUMN IF NOT EXISTS item_analysis_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS student_progress_enabled BOOLEAN,
    ADD COLUMN IF NOT EXISTS equation_editor_enabled BOOLEAN;
