/**
 * Map registry icon names → lucide-react components.
 * Only names referenced by the registry are included (tree-shake friendly).
 */

import type { ReactNode } from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  Accessibility,
  Activity,
  AlertTriangle,
  ArrowLeft,
  Award,
  BarChart3,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bot,
  Brain,
  Calendar,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  FileText,
  FlaskConical,
  FolderOpen,
  Gamepad2,
  GraduationCap,
  HeartPulse,
  Inbox,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Lightbulb,
  ListChecks,
  ListTodo,
  Medal,
  MessageSquare,
  MessagesSquare,
  MonitorUp,
  NotebookPen,
  PersonStanding,
  Pencil,
  PenLine,
  RotateCcw,
  Route,
  School,
  ScrollText,
  Send,
  Settings,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Table2,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Wallet,
  Wrench,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  Accessibility,
  Activity,
  AlertTriangle,
  ArrowLeft,
  Award,
  BarChart3,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bot,
  Brain,
  Calendar,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  FileText,
  FlaskConical,
  FolderOpen,
  Gamepad2,
  GraduationCap,
  HeartPulse,
  Inbox,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Lightbulb,
  ListChecks,
  ListTodo,
  Medal,
  MessageSquare,
  MessagesSquare,
  MonitorUp,
  NotebookPen,
  PersonStanding,
  Pencil,
  PenLine,
  RotateCcw,
  Route,
  School,
  ScrollText,
  Send,
  Settings,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Table2,
  Target,
  TrendingUp,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Wallet,
  Wrench,
}

export function navIcon(name: string, className = 'h-5 w-5'): ReactNode {
  const Icon = ICONS[name]
  if (!Icon) {
    if (import.meta.env.DEV) {
      console.warn(`[nav] unknown icon "${name}"`)
    }
    return <span className={className} aria-hidden />
  }
  return <Icon className={className} aria-hidden />
}

export function knownNavIconNames(): string[] {
  return Object.keys(ICONS)
}
