import type { NavDestination } from './types'

/**
 * Global (non-course, non-settings) shell destinations.
 * Priority is within-section; lower numbers appear first.
 */
export const GLOBAL_NAV: NavDestination[] = [
  // ── Primary (always top) ──────────────────────────────────────────
  {
    id: 'global.dashboard',
    route: '/',
    labelKey: 'nav.dest.dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    section: 'primary',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 10,
    audience: ['any'],
    essential: true,
    end: true,
    synonyms: ['home', 'overview'],
  },
  {
    id: 'global.courses',
    route: '/courses',
    labelKey: 'nav.dest.courses',
    label: 'Courses',
    icon: 'BookOpen',
    section: 'primary',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 20,
    audience: ['any'],
    essential: true,
    synonyms: ['classes', 'classrooms'],
  },
  {
    id: 'global.calendar',
    route: '/calendar',
    labelKey: 'nav.dest.calendar',
    label: 'Calendar',
    icon: 'Calendar',
    section: 'primary',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 30,
    audience: ['any'],
    essential: true,
    synonyms: ['schedule', 'agenda'],
  },
  {
    id: 'global.todos',
    route: '/todos',
    labelKey: 'nav.dest.todos',
    label: 'Todos',
    icon: 'ListTodo',
    section: 'primary',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 40,
    audience: ['any'],
    essential: true,
    synonyms: ['tasks', 'to-do', 'todo list'],
  },

  // ── Learning ──────────────────────────────────────────────────────
  {
    id: 'global.ask-ai',
    route: '/ai',
    labelKey: 'nav.dest.askAi',
    label: 'Ask AI',
    icon: 'Bot',
    section: 'learning',
    sectionV2: 'learning',
    priority: 10,
    audience: ['any'],
    featureFlag: 'ragNotebookEnabled',
    synonyms: ['assistant', 'chat', 'tutor'],
  },
  {
    id: 'global.course-catalog',
    route: '/catalog',
    labelKey: 'nav.dest.courseCatalog',
    label: 'Course catalog',
    icon: 'GraduationCap',
    section: 'learning',
    sectionV2: 'learning',
    priority: 20,
    audience: ['any'],
    featureFlag: 'ffCatalogIntegration',
    synonyms: ['catalogue', 'browse courses'],
  },
  {
    id: 'global.marketplace',
    route: '/marketplace',
    labelKey: 'nav.dest.marketplace',
    label: 'Marketplace',
    icon: 'Store',
    section: 'learning',
    sectionV2: 'learning',
    priority: 30,
    audience: ['any'],
    featureFlag: 'ffCourseMarketplace',
    synonyms: ['store', 'buy courses'],
  },
  {
    id: 'global.learning-paths',
    route: '/my-paths',
    labelKey: 'nav.dest.learningPaths',
    label: 'My learning paths',
    icon: 'Route',
    section: 'learning',
    sectionV2: 'learning',
    priority: 40,
    audience: ['any'],
    featureFlag: 'ffLearningPaths',
    synonyms: ['paths', 'programmes', 'programs'],
  },
  {
    id: 'global.reading-log',
    route: '/reading-log',
    labelKey: 'nav.dest.readingLog',
    label: 'Reading log',
    icon: 'Library',
    section: 'learning',
    sectionV2: 'learning',
    priority: 50,
    audience: ['any'],
    featureFlag: 'ffLibrary',
    synonyms: ['library log', 'books'],
  },
  {
    id: 'global.review',
    route: '/review',
    labelKey: 'nav.dest.reviewPractice',
    label: 'Review practice',
    icon: 'RotateCcw',
    section: 'learning',
    sectionV2: 'learning',
    priority: 60,
    audience: ['any'],
    synonyms: ['srs', 'spaced repetition', 'flashcards'],
  },
  {
    id: 'global.study-insights',
    route: '/me/study-insights',
    labelKey: 'nav.dest.studyInsights',
    label: 'Study insights',
    icon: 'Sparkles',
    section: 'learning',
    sectionV2: 'learning',
    priority: 70,
    audience: ['any'],
    featureFlag: 'selfReflectionEnabled',
    synonyms: ['reflection', 'study stats'],
  },

  // ── Notes & portfolio ─────────────────────────────────────────────
  {
    id: 'global.global-notebook',
    route: '/notebooks/global',
    labelKey: 'nav.dest.globalNotebook',
    label: 'Global notebook',
    icon: 'BookMarked',
    section: 'notes-portfolio',
    sectionV2: 'notes-portfolio',
    priority: 10,
    audience: ['any'],
    synonyms: ['cross-course notes'],
  },
  {
    id: 'global.notebooks',
    route: '/notebooks',
    labelKey: 'nav.dest.myNotebooks',
    label: 'My Notebooks',
    icon: 'NotebookPen',
    section: 'notes-portfolio',
    sectionV2: 'notes-portfolio',
    priority: 20,
    audience: ['any'],
    end: true,
    synonyms: ['notes', 'notebook'],
  },
  {
    id: 'global.portfolio',
    route: '/portfolios',
    labelKey: 'nav.dest.myPortfolio',
    label: 'My Portfolio',
    icon: 'FolderOpen',
    section: 'notes-portfolio',
    sectionV2: 'notes-portfolio',
    priority: 30,
    audience: ['any'],
    featureFlag: 'ffEportfolio',
    synonyms: ['eportfolio', 'e-portfolio'],
  },

  // ── Records ───────────────────────────────────────────────────────
  {
    id: 'global.advising-notes',
    route: '/advising-notes',
    labelKey: 'nav.dest.advisingNotes',
    label: 'Advising notes',
    icon: 'School',
    section: 'records',
    sectionV2: 'records',
    priority: 10,
    audience: ['any'],
    featureFlag: 'ffAdvisingIntegration',
  },
  {
    id: 'global.billing',
    route: '/me/billing',
    labelKey: 'nav.dest.billing',
    label: 'Billing',
    icon: 'CreditCard',
    section: 'records',
    sectionV2: 'records',
    priority: 20,
    audience: ['any'],
    featureFlag: 'ffStripeBilling',
    synonyms: ['payments', 'invoices'],
  },
  {
    id: 'global.ce-transcript',
    route: '/me/ce-transcript',
    labelKey: 'nav.dest.ceTranscript',
    label: 'CE transcript',
    icon: 'ScrollText',
    section: 'records',
    sectionV2: 'records',
    priority: 30,
    audience: ['any'],
    featureFlag: 'ffCeuTracking',
    synonyms: ['continuing education', 'ceu'],
  },
  {
    id: 'global.creator-earnings',
    route: '/me/creator/earnings',
    labelKey: 'nav.dest.creatorEarnings',
    label: 'Creator earnings',
    icon: 'DollarSign',
    section: 'records',
    sectionV2: 'records',
    priority: 40,
    audience: ['any'],
    featureFlag: 'ffRevenueShare',
  },
  {
    id: 'global.my-accommodations',
    route: '/me/accommodations',
    labelKey: 'nav.dest.myAccommodations',
    label: 'My access plan',
    icon: 'PersonStanding',
    section: 'records',
    sectionV2: 'records',
    priority: 50,
    audience: ['any'],
    featureFlag: 'ffAccessibilityIntake',
    synonyms: [
      'my accommodations',
      'accessibility needs',
      'disability services',
      'access plan',
    ],
  },
  // FR-6: disambiguated credential destinations (unique icons + labels).
  // Full merge into one Achievements hub is residual product work.
  {
    id: 'global.credential-wallet',
    route: '/me/wallet',
    labelKey: 'nav.dest.credentialWallet',
    label: 'Credential wallet',
    icon: 'Wallet',
    section: 'records',
    sectionV2: 'records',
    priority: 60,
    audience: ['any'],
    // Shown when any wallet-related flag is on — resolved in filter via composite.
    featureFlag: '_walletComposite',
    synonyms: ['wallet', 'badges wallet', 'diplomas', 'credentials wallet'],
  },
  {
    id: 'global.my-achievements',
    route: '/me/ccr',
    labelKey: 'nav.dest.myAchievements',
    label: 'Co-curricular record',
    icon: 'Medal',
    section: 'records',
    sectionV2: 'records',
    priority: 70,
    audience: ['any'],
    featureFlag: 'ffCoCurricularTranscript',
    synonyms: ['achievements', 'my achievements', 'ccr', 'co curricular'],
  },
  {
    id: 'global.my-credentials',
    route: '/me/credentials',
    labelKey: 'nav.dest.myCredentials',
    label: 'Completion credentials',
    icon: 'Award',
    section: 'records',
    sectionV2: 'records',
    priority: 80,
    audience: ['any'],
    featureFlag: 'ffCompletionCredentials',
    synonyms: ['my credentials', 'certificates', 'completion certificates'],
  },
  {
    id: 'global.my-purchases',
    route: '/me/purchases',
    labelKey: 'nav.dest.myPurchases',
    label: 'My purchases',
    icon: 'ShoppingBag',
    section: 'records',
    sectionV2: 'records',
    priority: 90,
    audience: ['any'],
    featureFlag: 'ffCourseMarketplace',
    synonyms: ['orders', 'bought'],
  },
  {
    id: 'global.research-studies',
    route: '/me/research-studies',
    labelKey: 'nav.dest.researchStudies',
    label: 'Research studies',
    icon: 'FlaskConical',
    section: 'records',
    sectionV2: 'records',
    priority: 100,
    audience: ['any'],
    featureFlag: 'ffResearchConsent',
    synonyms: ['consent', 'studies'],
  },
  {
    id: 'global.transcripts',
    route: '/transcripts',
    labelKey: 'nav.dest.transcripts',
    label: 'Transcripts',
    icon: 'FileText',
    section: 'records',
    sectionV2: 'records',
    priority: 110,
    audience: ['any'],
    featureFlag: 'ffTranscripts',
    synonyms: ['academic record', 'official transcript'],
  },

  // ── Family ────────────────────────────────────────────────────────
  {
    id: 'global.parent-conferences',
    route: '/parent/conferences',
    labelKey: 'nav.dest.conferenceBooking',
    label: 'Conference booking',
    icon: 'CalendarDays',
    section: 'family',
    sectionV2: 'family',
    priority: 10,
    audience: ['parent'],
    featureFlag: 'ffConferenceScheduling',
    synonyms: ['parent conferences', 'meetings'],
  },
  {
    id: 'global.parent-dashboard',
    route: '/parent',
    labelKey: 'nav.dest.familyDashboard',
    label: 'Family dashboard',
    icon: 'UsersRound',
    section: 'family',
    sectionV2: 'family',
    priority: 20,
    audience: ['parent'],
    permission: 'parent.dashboard',
    synonyms: ['parent portal', 'guardian'],
  },

  // ── Administration ────────────────────────────────────────────────
  {
    id: 'global.assign-parents',
    route: '/assign-parents',
    labelKey: 'nav.dest.assignParents',
    label: 'Assign parents',
    icon: 'UserPlus',
    section: 'administration',
    sectionV2: 'administration',
    priority: 10,
    audience: ['admin', 'instructor'],
    featureFlag: 'ffParentPortal',
    // permission resolved dynamically (parent links OR rbac)
    permission: '_assignParents',
  },
  {
    id: 'global.accommodation-audit',
    route: '/admin/accommodations/audit',
    labelKey: 'nav.dest.accommodationAudit',
    label: 'Accommodation audit',
    icon: 'ClipboardCheck',
    section: 'administration',
    sectionV2: 'administration',
    priority: 20,
    audience: ['admin'],
    permission: 'accommodations.manage',
    featureFlag: 'accommodationsEngineEnabled',
  },
  {
    id: 'global.accommodations',
    route: '/admin/accommodations',
    labelKey: 'nav.dest.accommodations',
    label: 'Accommodations',
    icon: 'Accessibility',
    section: 'administration',
    sectionV2: 'administration',
    priority: 30,
    audience: ['admin'],
    permission: 'accommodations.manage',
  },
  {
    id: 'global.reports',
    route: '/reports',
    labelKey: 'nav.dest.platformReports',
    label: 'Platform reports',
    icon: 'BarChart3',
    section: 'administration',
    sectionV2: 'administration',
    priority: 40,
    audience: ['admin'],
    permission: 'reports.view',
    synonyms: ['reports', 'analytics', 'platform analytics'],
  },

  // ── Account ───────────────────────────────────────────────────────
  {
    id: 'global.inbox',
    route: '/inbox',
    labelKey: 'nav.dest.inbox',
    label: 'Inbox',
    icon: 'Inbox',
    section: 'account',
    sectionV2: 'account',
    primaryV2: true,
    priority: 10,
    audience: ['any'],
    essential: true,
    synonyms: ['messages', 'mail'],
  },
  {
    id: 'global.settings',
    route: '/settings',
    labelKey: 'nav.dest.settings',
    label: 'Settings',
    icon: 'Settings',
    section: 'account',
    sectionV2: 'account',
    primaryV2: true,
    priority: 20,
    audience: ['any'],
    essential: true,
    synonyms: ['preferences', 'account settings'],
  },
]
