import type { NavDestination } from './types'

/**
 * In-course destinations. Routes use `:courseCode` placeholder.
 *
 * Legacy sections match current IA. V2 uses task-based Teach / Engage /
 * Assess & analyse / Manage (instructor) and Participate / My work (student).
 * Gradebook priority is intentionally first in grades-insights (AC-1).
 */
export const COURSE_NAV_CORE: NavDestination[] = [
  {
    id: 'course.back',
    route: '/courses',
    labelKey: 'nav.dest.back',
    label: 'Back',
    icon: 'ArrowLeft',
    section: 'primary',
    sectionV2: 'primary',
    priority: 0,
    audience: ['any'],
    essential: true,
    utility: true,
    indexInPalette: false,
  },
  {
    id: 'course.dashboard',
    route: '/courses/:courseCode',
    labelKey: 'nav.dest.dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    section: 'primary',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 10,
    audience: ['any'],
    essential: true,
    end: true,
    synonyms: ['home', 'course home', 'overview'],
  },
  {
    id: 'course.checklist',
    route: '/courses/:courseCode/checklist',
    labelKey: 'nav.dest.checklist',
    label: 'Checklist',
    icon: 'ListTodo',
    section: 'primary',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 15,
    audience: ['instructor'],
    // instructor + manage permission resolved in filter
    permission: '_courseManage',
    essential: true,
    synonyms: ['setup checklist', 'course checklist'],
  },

  // ── Content (legacy) / Teach (V2) ─────────────────────────────────
  {
    id: 'course.files',
    route: '/courses/:courseCode/files',
    labelKey: 'nav.dest.files',
    label: 'Files',
    icon: 'FolderOpen',
    section: 'content',
    sectionV2: 'teach',
    priority: 10,
    audience: ['instructor'],
    courseFeature: 'filesEnabled',
    permission: '_courseManage',
    synonyms: ['course files', 'documents'],
  },
  {
    id: 'course.modules',
    route: '/courses/:courseCode/modules',
    labelKey: 'nav.dest.modules',
    label: 'Modules',
    icon: 'Layers',
    section: 'content',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 20,
    audience: ['any'],
    essential: true,
    synonyms: ['content', 'lessons', 'units'],
  },
  {
    id: 'course.syllabus',
    route: '/courses/:courseCode/syllabus',
    labelKey: 'nav.dest.syllabus',
    label: 'Syllabus',
    icon: 'FileText',
    section: 'content',
    sectionV2: 'teach',
    priority: 30,
    audience: ['any'],
    synonyms: ['outline', 'course outline'],
  },
  {
    id: 'course.whiteboard',
    route: '/courses/:courseCode/whiteboard',
    labelKey: 'nav.dest.whiteboard',
    label: 'Whiteboard',
    icon: 'Pencil',
    section: 'collaboration',
    sectionV2: 'teach',
    priority: 80,
    audience: ['instructor'],
    courseFeature: 'whiteboardEnabled',
    permission: '_courseManage',
  },
  {
    id: 'course.question-bank',
    route: '/courses/:courseCode/questions',
    labelKey: 'nav.dest.questionBank',
    label: 'Question bank',
    icon: 'ListChecks',
    section: 'assessment',
    sectionV2: 'teach',
    priority: 40,
    audience: ['instructor'],
    courseFeature: 'questionBankEnabled',
    permission: '_courseQuestionBank',
    synonyms: ['questions', 'item bank', 'quiz questions'],
  },
  {
    id: 'course.live-quizzes',
    route: '/courses/:courseCode/live-quizzes',
    labelKey: 'nav.dest.liveQuizzes',
    label: 'Live Quizzes',
    icon: 'Gamepad2',
    section: 'assessment',
    sectionV2: 'teach',
    priority: 50,
    audience: ['any'],
    courseFeature: 'interactiveQuizzesEnabled',
    synonyms: ['kahoot', 'live quiz', 'polling'],
  },
  {
    id: 'course.content-tools',
    route: '/courses/:courseCode/content-tools',
    labelKey: 'nav.dest.contentTools',
    label: 'Content Tools',
    icon: 'Wrench',
    section: 'grades-insights',
    sectionV2: 'teach',
    priority: 90,
    audience: ['instructor'],
    courseFeature: 'contentToolsEnabled',
    permission: '_courseGradebook',
    synonyms: ['tools', 'h5p tools'],
  },
  {
    id: 'course.screen-share',
    route: '/courses/:courseCode/screen-share',
    labelKey: 'nav.dest.screenShare',
    label: 'Screen share',
    icon: 'MonitorUp',
    section: 'assessment',
    sectionV2: 'teach',
    priority: 60,
    audience: ['any'],
    courseFeature: 'screenShareEnabled',
  },

  // ── Collaboration (legacy) / Engage (V2) ──────────────────────────
  {
    id: 'course.boards',
    route: '/courses/:courseCode/boards',
    labelKey: 'nav.dest.boards',
    label: 'Boards',
    icon: 'LayoutGrid',
    section: 'collaboration',
    sectionV2: 'engage',
    priority: 10,
    audience: ['any'],
    courseFeature: 'visualBoardsEnabled',
    synonyms: ['visual boards', 'canvas boards'],
  },
  {
    id: 'course.collab-docs',
    route: '/courses/:courseCode/collab-docs',
    labelKey: 'nav.dest.collabDocs',
    label: 'Collab docs',
    icon: 'PenLine',
    section: 'collaboration',
    sectionV2: 'engage',
    priority: 20,
    audience: ['any'],
    courseFeature: 'collabDocsEnabled',
    synonyms: ['collaborative docs', 'shared docs'],
  },
  {
    id: 'course.discussions',
    route: '/courses/:courseCode/discussions',
    labelKey: 'nav.dest.discussions',
    label: 'Discussions',
    icon: 'MessagesSquare',
    section: 'collaboration',
    sectionV2: 'engage',
    priority: 30,
    audience: ['any'],
    courseFeature: 'discussionsEnabled',
    synonyms: ['forums', 'posts'],
  },
  {
    id: 'course.feed',
    route: '/courses/:courseCode/feed',
    labelKey: 'nav.dest.feed',
    label: 'Feed',
    icon: 'MessageSquare',
    section: 'collaboration',
    sectionV2: 'engage',
    priority: 40,
    audience: ['any'],
    courseFeature: 'feedEnabled',
    synonyms: ['announcements', 'course feed'],
  },
  {
    id: 'course.groups',
    route: '/courses/:courseCode/groups',
    labelKey: 'nav.dest.groups',
    label: 'Groups',
    icon: 'UsersRound',
    section: 'collaboration',
    sectionV2: 'engage',
    priority: 50,
    audience: ['any'],
    courseFeature: 'groupSpacesEnabled',
    synonyms: ['group spaces', 'teams'],
  },
  {
    id: 'course.live-sessions',
    route: '/courses/:courseCode/live',
    labelKey: 'nav.dest.liveSessions',
    label: 'Live Sessions',
    icon: 'Video',
    section: 'collaboration',
    sectionV2: 'engage',
    priority: 60,
    audience: ['any'],
    courseFeature: 'liveSessionsEnabled',
    synonyms: ['virtual classroom', 'zoom', 'meet'],
  },
  {
    id: 'course.office-hours',
    route: '/courses/:courseCode/office-hours',
    labelKey: 'nav.dest.officeHours',
    label: 'Office Hours',
    icon: 'Clock',
    section: 'collaboration',
    sectionV2: 'engage',
    priority: 70,
    audience: ['any'],
    courseFeature: 'officeHoursEnabled',
    synonyms: ['office hour', 'drop-in'],
  },

]
