import type { NavDestination } from './types'

/** Student learning, grades/insights, people, and manage destinations. */
export const COURSE_NAV_SECONDARY: NavDestination[] = [
  // ── Your learning (legacy student) / My work (V2) ─────────────────
  {
    id: 'course.attendance',
    route: '/courses/:courseCode/attendance',
    labelKey: 'nav.dest.attendance',
    label: 'Attendance',
    icon: 'ClipboardList',
    section: 'your-learning',
    sectionV2: 'my-work',
    priority: 10,
    audience: ['any'],
    courseFeature: 'attendanceEnabled',
    synonyms: ['roll call', 'presence'],
  },
  {
    id: 'course.calendar',
    route: '/courses/:courseCode/calendar',
    labelKey: 'nav.dest.calendar',
    label: 'Calendar',
    icon: 'Calendar',
    section: 'your-learning',
    sectionV2: 'my-work',
    priority: 20,
    audience: ['any'],
    courseFeature: 'calendarEnabled',
    synonyms: ['schedule', 'due dates'],
  },
  {
    id: 'course.my-grades',
    route: '/courses/:courseCode/my-grades',
    labelKey: 'nav.dest.myGrades',
    label: 'My grades',
    icon: 'Award',
    section: 'your-learning',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 30,
    audience: ['student'],
    permission: '_courseMyGrades',
    synonyms: ['marks', 'scores', 'my marks', 'grades'],
  },
  {
    id: 'course.notebook',
    route: '/courses/:courseCode/notebook',
    labelKey: 'nav.dest.notebook',
    label: 'Notebook',
    icon: 'NotebookPen',
    section: 'your-learning',
    sectionV2: 'my-work',
    priority: 40,
    audience: ['any'],
    courseFeature: 'notebookEnabled',
    synonyms: ['course notes'],
  },

  // ── Grades & insights (legacy) / Assess & analyse (V2) ────────────
  // Gradebook first by priority (AC-1) — never alphabetical.
  {
    id: 'course.gradebook',
    route: '/courses/:courseCode/gradebook',
    labelKey: 'nav.dest.gradebook',
    label: 'Gradebook',
    icon: 'Table2',
    section: 'grades-insights',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 1,
    audience: ['instructor'],
    permission: '_courseGradebook',
    essential: true,
    synonyms: ['grades', 'marks', 'scores', 'grade book', 'markbook'],
  },
  {
    id: 'course.at-risk',
    route: '/courses/:courseCode/at-risk',
    labelKey: 'nav.dest.atRisk',
    label: 'At-risk',
    icon: 'AlertTriangle',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 10,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: '_atRisk',
    synonyms: ['at risk', 'struggling students'],
  },
  {
    id: 'course.behavior',
    route: '/courses/:courseCode/behavior',
    labelKey: 'nav.dest.behavior',
    label: 'Behavior',
    icon: 'HeartPulse',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 20,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: 'ffClassroomSignals',
    synonyms: ['behaviour', 'classroom signals'],
  },
  {
    id: 'course.evaluation-results',
    route: '/courses/:courseCode/evaluation-results',
    labelKey: 'nav.dest.evaluationResults',
    label: 'Evaluation results',
    icon: 'Star',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 30,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: 'ffCourseEvaluations',
    synonyms: ['course evals', 'evaluations'],
  },
  {
    id: 'course.event-log',
    route: '/courses/:courseCode/event-log',
    labelKey: 'nav.dest.eventLog',
    label: 'Event log',
    icon: 'Activity',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 40,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: '_xapi',
    synonyms: ['xapi', 'activity log', 'lrs'],
  },
  {
    id: 'course.final-grades',
    route: '/courses/:courseCode/final-grades',
    labelKey: 'nav.dest.finalGrades',
    label: 'Final grades',
    icon: 'Send',
    section: 'grades-insights',
    sectionV2: 'manage',
    priority: 20,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: 'ffGradeSubmission',
    synonyms: ['submit grades', 'grade submission'],
  },
  {
    id: 'course.mastery-heatmap',
    route: '/courses/:courseCode/mastery-heatmap',
    labelKey: 'nav.dest.masteryHeatmap',
    label: 'Mastery heatmap',
    icon: 'TrendingUp',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 50,
    audience: ['instructor'],
    permission: '_courseGradebook',
    courseFeature: 'sbgEnabled',
    synonyms: ['mastery', 'heatmap'],
  },
  {
    id: 'course.outcomes-report',
    route: '/courses/:courseCode/outcomes-report',
    labelKey: 'nav.dest.outcomesReport',
    label: 'Outcomes report',
    icon: 'Target',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 60,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: '_outcomesReport',
    synonyms: ['outcomes', 'learning outcomes'],
  },
  {
    id: 'course.reading-dashboard',
    route: '/courses/:courseCode/reading-dashboard',
    labelKey: 'nav.dest.readingDashboard',
    label: 'Reading dashboard',
    icon: 'Library',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 70,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: 'ffLibrary',
  },
  {
    id: 'course.report-cards',
    route: '/courses/:courseCode/report-cards',
    labelKey: 'nav.dest.reportCards',
    label: 'Report cards',
    icon: 'ClipboardCheck',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 80,
    audience: ['instructor'],
    permission: '_courseGradebook',
    courseFeature: 'reportCardsEnabled',
  },
  {
    id: 'course.reports',
    route: '/courses/:courseCode/reports',
    labelKey: 'nav.dest.courseReports',
    label: 'Course reports',
    icon: 'BarChart3',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 90,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: '_studentProgress',
    synonyms: ['reports', 'progress reports', 'student progress'],
  },
  {
    id: 'course.standards-coverage',
    route: '/courses/:courseCode/standards-coverage',
    labelKey: 'nav.dest.standardsCoverage',
    label: 'Standards coverage',
    icon: 'BookMarked',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 100,
    audience: ['instructor'],
    courseFeature: 'standardsAlignmentEnabled',
    permission: '_courseStandards',
    synonyms: ['coverage map', 'standards map'],
  },
  {
    id: 'course.standards-gradebook',
    route: '/courses/:courseCode/standards-gradebook',
    labelKey: 'nav.dest.standardsGradebook',
    label: 'Standards gradebook',
    icon: 'BookOpenCheck',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 110,
    audience: ['instructor'],
    courseFeature: 'sbgEnabled',
    permission: '_courseGradebook',
    synonyms: ['sbg', 'standards based grading'],
  },
  {
    id: 'course.whats-working',
    route: '/courses/:courseCode/whats-working',
    labelKey: 'nav.dest.whatsWorking',
    label: "What's working",
    icon: 'Lightbulb',
    section: 'grades-insights',
    sectionV2: 'assess-analyse',
    priority: 120,
    audience: ['instructor'],
    permission: '_courseGradebook',
    featureFlag: 'instructorInsightsEnabled',
    synonyms: ['instructor insights', 'whats working'],
  },
  {
    id: 'course.misconceptions',
    route: '/courses/:courseCode/misconception-report',
    labelKey: 'nav.dest.misconceptions',
    label: 'Misconceptions',
    icon: 'Brain',
    section: 'assessment',
    sectionV2: 'assess-analyse',
    priority: 130,
    audience: ['instructor'],
    courseFeature: 'questionBankEnabled',
    permission: '_courseQuestionBank',
    synonyms: ['misconception report'],
  },

  // ── People ────────────────────────────────────────────────────────
  {
    id: 'course.enrollments',
    route: '/courses/:courseCode/enrollments',
    labelKey: 'nav.dest.enrollments',
    label: 'Enrollments',
    icon: 'Users',
    section: 'people',
    sectionV2: 'primary',
    primaryV2: true,
    priority: 10,
    audience: ['instructor'],
    permission: '_courseEnrollments',
    synonyms: ['people', 'roster', 'students', 'class list'],
  },

  // ── Manage ────────────────────────────────────────────────────────
  {
    id: 'course.settings',
    route: '/courses/:courseCode/settings/general',
    labelKey: 'nav.dest.settings',
    label: 'Settings',
    icon: 'Settings',
    section: 'manage',
    sectionV2: 'manage',
    priority: 10,
    audience: ['instructor'],
    permission: '_courseManage',
    activePathPrefix: '/courses/:courseCode/settings',
    synonyms: ['course settings', 'preferences'],
  },
]
