import type { NavSectionId, NavSectionMeta } from './types'

/** Section metadata for both legacy and V2 taxonomies. */
export const NAV_SECTIONS: Record<NavSectionId, NavSectionMeta> = {
  primary: {
    id: 'primary',
    labelKey: 'nav.section.primary',
    label: '',
    order: 0,
    orderV2: 0,
  },
  pinned: {
    id: 'pinned',
    labelKey: 'nav.section.pinned',
    label: 'Pinned',
    order: -20,
    orderV2: -20,
  },
  recent: {
    id: 'recent',
    labelKey: 'nav.section.recent',
    label: 'Recent',
    order: -10,
    orderV2: -10,
  },
  content: {
    id: 'content',
    labelKey: 'nav.section.content',
    label: 'Content',
    order: 10,
    orderV2: 100,
    visibleBudget: 8,
  },
  collaboration: {
    id: 'collaboration',
    labelKey: 'nav.section.collaboration',
    label: 'Collaboration',
    order: 20,
    orderV2: 100,
    visibleBudget: 8,
  },
  'your-learning': {
    id: 'your-learning',
    labelKey: 'nav.section.yourLearning',
    label: 'Your learning',
    order: 30,
    orderV2: 100,
  },
  assessment: {
    id: 'assessment',
    labelKey: 'nav.section.assessment',
    label: 'Assessment',
    order: 40,
    orderV2: 100,
  },
  'grades-insights': {
    id: 'grades-insights',
    labelKey: 'nav.section.gradesInsights',
    label: 'Grades & insights',
    order: 50,
    orderV2: 100,
    visibleBudget: 6,
  },
  people: {
    id: 'people',
    labelKey: 'nav.section.people',
    label: 'People',
    order: 60,
    orderV2: 100,
  },
  manage: {
    id: 'manage',
    labelKey: 'nav.section.manage',
    label: 'Manage',
    order: 70,
    orderV2: 50,
    visibleBudget: 8,
  },
  learning: {
    id: 'learning',
    labelKey: 'nav.section.learning',
    label: 'Learning',
    order: 10,
    orderV2: 10,
  },
  'notes-portfolio': {
    id: 'notes-portfolio',
    labelKey: 'nav.section.notesPortfolio',
    label: 'Notes & portfolio',
    order: 20,
    orderV2: 20,
  },
  records: {
    id: 'records',
    labelKey: 'nav.section.records',
    label: 'Records',
    order: 30,
    orderV2: 30,
    visibleBudget: 6,
  },
  family: {
    id: 'family',
    labelKey: 'nav.section.family',
    label: 'Family',
    order: 40,
    orderV2: 40,
  },
  administration: {
    id: 'administration',
    labelKey: 'nav.section.administration',
    label: 'Administration',
    order: 50,
    orderV2: 50,
  },
  account: {
    id: 'account',
    labelKey: 'nav.section.account',
    label: 'Account',
    order: 60,
    orderV2: 60,
  },
  teach: {
    id: 'teach',
    labelKey: 'nav.section.teach',
    label: 'Teach',
    order: 100,
    orderV2: 10,
    visibleBudget: 6,
  },
  engage: {
    id: 'engage',
    labelKey: 'nav.section.engage',
    label: 'Engage',
    order: 100,
    orderV2: 20,
    visibleBudget: 6,
  },
  'assess-analyse': {
    id: 'assess-analyse',
    labelKey: 'nav.section.assessAnalyse',
    label: 'Assess & analyse',
    order: 100,
    orderV2: 30,
    visibleBudget: 6,
  },
  participate: {
    id: 'participate',
    labelKey: 'nav.section.participate',
    label: 'Participate',
    order: 100,
    orderV2: 10,
    visibleBudget: 6,
  },
  'my-work': {
    id: 'my-work',
    labelKey: 'nav.section.myWork',
    label: 'My work',
    order: 100,
    orderV2: 20,
  },
  'user-settings': {
    id: 'user-settings',
    labelKey: 'nav.section.userSettings',
    label: 'User Settings',
    order: 10,
    orderV2: 10,
  },
  'org-settings': {
    id: 'org-settings',
    labelKey: 'nav.section.orgSettings',
    label: 'Organisation',
    order: 20,
    orderV2: 20,
  },
  platform: {
    id: 'platform',
    labelKey: 'nav.section.platform',
    label: 'Platform',
    order: 30,
    orderV2: 30,
  },
  'course-setup': {
    id: 'course-setup',
    labelKey: 'nav.section.courseSetup',
    label: 'Course setup',
    order: 10,
    orderV2: 10,
  },
  'grading-outcomes': {
    id: 'grading-outcomes',
    labelKey: 'nav.section.gradingOutcomes',
    label: 'Grading & outcomes',
    order: 20,
    orderV2: 20,
  },
  'access-localization': {
    id: 'access-localization',
    labelKey: 'nav.section.accessLocalization',
    label: 'Access & localization',
    order: 30,
    orderV2: 30,
  },
  'content-data': {
    id: 'content-data',
    labelKey: 'nav.section.contentData',
    label: 'Content & data',
    order: 40,
    orderV2: 40,
  },
  lifecycle: {
    id: 'lifecycle',
    labelKey: 'nav.section.lifecycle',
    label: 'Lifecycle',
    order: 50,
    orderV2: 50,
  },
  'admin-tools': {
    id: 'admin-tools',
    labelKey: 'nav.section.adminTools',
    label: 'Admin',
    order: 40,
    orderV2: 40,
  },
  more: {
    id: 'more',
    labelKey: 'nav.section.more',
    label: 'More',
    order: 999,
    orderV2: 999,
  },
}

export function sectionOrder(id: NavSectionId, v2: boolean): number {
  const meta = NAV_SECTIONS[id]
  return v2 ? meta.orderV2 : meta.order
}
