export type FieldSource = 'environment' | 'database' | 'default'

export type PlatformSettingsPayload = {
  samlSsoEnabled: boolean
  samlPublicBaseUrl: string
  samlSpEntityId: string
  samlSpX509Pem: string
  samlSpPrivateKeyPem: string
  annotationEnabled: boolean
  feedbackMediaEnabled: boolean
  blindGradingEnabled: boolean
  moderatedGradingEnabled: boolean
  originalityDetectionEnabled: boolean
  originalityStubExternal: boolean
  gradePostingPoliciesEnabled: boolean
  gradebookCsvEnabled: boolean
  resubmissionWorkflowEnabled: boolean
  ltiEnabled: boolean
  oneRosterEnabled: boolean
  scimEnabled: boolean
  studentProgressEnabled: boolean
  selfReflectionEnabled: boolean
  outcomesReportEnabled: boolean
  atRiskAlertsEnabled: boolean
  h5pEnabled: boolean
  scormIngestionEnabled: boolean
  oerLibraryEnabled: boolean
  oerStub: boolean
  itemAnalysisEnabled: boolean
  xapiEmissionEnabled: boolean
  equationEditorEnabled: boolean
  readingLevelEnabled: boolean
  graderAgentEnabled: boolean
  graderAgentReviewInboxEnabled: boolean
  graderAgentSuggestModeEnabled: boolean
  graderAgentTextEntryGradingEnabled: boolean
  graderAgentVisionGradingEnabled: boolean
  graderAgentRunFiltersEnabled: boolean
  graderAgentCostEstimateEnabled: boolean
  graderAgentCancelRunEnabled: boolean
  codeExecutionEnabled: boolean
  speechToTextEnabled: boolean
  accommodationsEngineEnabled: boolean
  ffAccommodationsEngine: boolean
  ffBookstoreIntegration: boolean
  ffCoCurricularTranscript: boolean
  ffEportfolio: boolean
  ffTranscripts: boolean
  ffWebhooks: boolean
  adminConsoleEnabled: boolean
  impersonationEnabled: boolean
  bulkCsvImportEnabled: boolean
  adminSearchEnabled: boolean
  customFieldsEnabled: boolean
  seatManagementEnabled: boolean
  emailTemplateEditorEnabled: boolean
  maintenanceBannerEnabled: boolean
  ffZapierConnector: boolean
  ffAdvisingIntegration: boolean
  ffResearchConsent: boolean
  ffAccessibilityIntake: boolean
  ffCeuTracking: boolean
  ffConsortiumSharing: boolean
  ffStripeBilling: boolean
  ffPaymentsEnabled: boolean
  ffRevenueShare: boolean
  ffTaxCollection: boolean
  ffLearningPaths: boolean
  ffConditionalRelease: boolean
  ffPeerReview: boolean
  ffCompletionCredentials: boolean
  ffOnboardingFlow: boolean
  ffWhatifGrades: boolean
  ffGradeCurving: boolean
  ffAiStudyBuddy: boolean
  ffPersistentTutor: boolean
  ffApiTokens: boolean
  ffCalendarFeeds: boolean
  ffRedisCache: boolean
  ffAcademicCalendar: boolean
  ffClassroomSignals: boolean
  ffConferenceScheduling: boolean
  ffBotSlack: boolean
  ffBotTeams: boolean
  ffBotDiscord: boolean
  ffBroadcasts: boolean
  ffCourseEvaluations: boolean
  ffSisIntegration: boolean
  ffGamification: boolean
  ffDemographics: boolean
  ffEnrollmentStateMachine: boolean
  ffIncompleteGradeWorkflow: boolean
  ffGradeSubmission: boolean
  ffCatalogIntegration: boolean
  ffLibrary: boolean
  ffLibraryIntegration: boolean
  ffReadingPreferences: boolean
  ffUiMode: boolean
  ffReadAloud: boolean
  ffAltTextEnforcement: boolean
  ffProctoringIntegration: boolean
  ffCourseReviews: boolean
  ffParentPortal: boolean
  ffReportCards: boolean
  ffPublicCatalog: boolean
  ffSelfPacedMode: boolean
  ffPublicApi: boolean
  ffContentFilterIntegration: boolean
  ffPlagiarismChecks: boolean
  ffStudyReminders: boolean
  translationMemoryEnabled: boolean
  storageQuotasEnabled: boolean
  avScanningEnabled: boolean
  virtualClassroomEnabled: boolean
  sessionManagementUiEnabled: boolean
  mfaEnabled: boolean
  mfaEnforcement: 'none' | 'all' | 'staff'
  smtpHost: string
  smtpPort: number
  smtpFrom: string
  smtpUser: string
  smtpPassword: string
  sources: {
    samlSsoEnabled: FieldSource
    samlPublicBaseUrl: FieldSource
    samlSpEntityId: FieldSource
    samlSpX509Pem: FieldSource
    samlSpPrivateKeyPem: FieldSource
    annotationEnabled: FieldSource
    feedbackMediaEnabled: FieldSource
    blindGradingEnabled: FieldSource
    moderatedGradingEnabled: FieldSource
    originalityDetectionEnabled: FieldSource
    originalityStubExternal: FieldSource
    gradePostingPoliciesEnabled: FieldSource
    gradebookCsvEnabled: FieldSource
    resubmissionWorkflowEnabled: FieldSource
    ltiEnabled: FieldSource
    oneRosterEnabled: FieldSource
    scimEnabled: FieldSource
    mfaEnabled: FieldSource
    mfaEnforcement: FieldSource
    smtpHost: FieldSource
    smtpPort: FieldSource
    smtpFrom: FieldSource
    smtpUser: FieldSource
    smtpPassword: FieldSource
  }
}
