#!/usr/bin/env bash
# Sync clients/mobile-dev.env to iOS and Android local developer API settings.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/mobile-dev.env"
EXAMPLE_FILE="$ROOT/mobile-dev.env.example"

if [[ ! -f "$ENV_FILE" ]]; then
  cp "$EXAMPLE_FILE" "$ENV_FILE"
  echo "Created $ENV_FILE from example."
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

API_HOST="${API_HOST:-localhost}"
API_PORT="${API_PORT:-8080}"

resolve_ios_url() {
  case "$API_HOST" in
    localhost | 127.0.0.1) echo "http://127.0.0.1:${API_PORT}" ;;
    *) echo "http://${API_HOST}:${API_PORT}" ;;
  esac
}

resolve_android_url() {
  case "$API_HOST" in
    localhost | 127.0.0.1) echo "http://10.0.2.2:${API_PORT}" ;;
    *) echo "http://${API_HOST}:${API_PORT}" ;;
  esac
}

to_xcconfig_url() {
  # xcconfig treats // as a comment; use http:/$()/host form.
  echo "$1" | sed 's|://|:/$()/|'
}

IOS_URL="$(resolve_ios_url)"
ANDROID_URL="$(resolve_android_url)"

IOS_CONFIG_DIR="$ROOT/ios/Config"
mkdir -p "$IOS_CONFIG_DIR"
cat >"$IOS_CONFIG_DIR/Development.local.xcconfig" <<EOF
// Generated by clients/scripts/setup-mobile-dev.sh — edit mobile-dev.env and re-run the script.
API_BASE_URL = $(to_xcconfig_url "$IOS_URL")
EOF

ANDROID_DIR="$ROOT/android"
LOCAL_PROPS="$ANDROID_DIR/local.properties"
TMP_PROPS="$(mktemp)"

if [[ -f "$LOCAL_PROPS" ]]; then
  grep -v '^API_BASE_URL=' "$LOCAL_PROPS" >"$TMP_PROPS" || true
else
  : >"$TMP_PROPS"
fi

echo "API_BASE_URL=$ANDROID_URL" >>"$TMP_PROPS"
mv "$TMP_PROPS" "$LOCAL_PROPS"

echo "Synced mobile dev API configuration:"
echo "  iOS:     $IOS_URL"
echo "  Android: $ANDROID_URL"
