package iso

// SoAControl is one Annex A control tracked in the Statement of Applicability.
type SoAControl struct {
	ID    string
	Theme string
	Title string
}

// AnnexAControls lists all ISO/IEC 27001:2022 Annex A controls (93 total).
var AnnexAControls = []SoAControl{
	// Organizational (37)
	{ID: "A.5.1", Theme: "organizational", Title: "Policies for information security"},
	{ID: "A.5.2", Theme: "organizational", Title: "Information security roles and responsibilities"},
	{ID: "A.5.3", Theme: "organizational", Title: "Segregation of duties"},
	{ID: "A.5.4", Theme: "organizational", Title: "Management responsibilities"},
	{ID: "A.5.5", Theme: "organizational", Title: "Contact with authorities"},
	{ID: "A.5.6", Theme: "organizational", Title: "Contact with special interest groups"},
	{ID: "A.5.7", Theme: "organizational", Title: "Threat intelligence"},
	{ID: "A.5.8", Theme: "organizational", Title: "Information security in project management"},
	{ID: "A.5.9", Theme: "organizational", Title: "Inventory of information and other associated assets"},
	{ID: "A.5.10", Theme: "organizational", Title: "Acceptable use of information and other associated assets"},
	{ID: "A.5.11", Theme: "organizational", Title: "Return of assets"},
	{ID: "A.5.12", Theme: "organizational", Title: "Classification of information"},
	{ID: "A.5.13", Theme: "organizational", Title: "Labelling of information"},
	{ID: "A.5.14", Theme: "organizational", Title: "Information transfer"},
	{ID: "A.5.15", Theme: "organizational", Title: "Access control"},
	{ID: "A.5.16", Theme: "organizational", Title: "Identity management"},
	{ID: "A.5.17", Theme: "organizational", Title: "Authentication information"},
	{ID: "A.5.18", Theme: "organizational", Title: "Access rights"},
	{ID: "A.5.19", Theme: "organizational", Title: "Information security in supplier relationships"},
	{ID: "A.5.20", Theme: "organizational", Title: "Addressing information security within supplier agreements"},
	{ID: "A.5.21", Theme: "organizational", Title: "Managing information security in the ICT supply chain"},
	{ID: "A.5.22", Theme: "organizational", Title: "Monitoring, review and change management of supplier services"},
	{ID: "A.5.23", Theme: "organizational", Title: "Information security for use of cloud services"},
	{ID: "A.5.24", Theme: "organizational", Title: "Information security incident management planning and preparation"},
	{ID: "A.5.25", Theme: "organizational", Title: "Assessment and decision on information security events"},
	{ID: "A.5.26", Theme: "organizational", Title: "Response to information security incidents"},
	{ID: "A.5.27", Theme: "organizational", Title: "Learning from information security incidents"},
	{ID: "A.5.28", Theme: "organizational", Title: "Collection of evidence"},
	{ID: "A.5.29", Theme: "organizational", Title: "Information security during disruption"},
	{ID: "A.5.30", Theme: "organizational", Title: "ICT readiness for business continuity"},
	{ID: "A.5.31", Theme: "organizational", Title: "Legal, statutory, regulatory and contractual requirements"},
	{ID: "A.5.32", Theme: "organizational", Title: "Intellectual property rights"},
	{ID: "A.5.33", Theme: "organizational", Title: "Protection of records"},
	{ID: "A.5.34", Theme: "organizational", Title: "Privacy and protection of PII"},
	{ID: "A.5.35", Theme: "organizational", Title: "Independent review of information security"},
	{ID: "A.5.36", Theme: "organizational", Title: "Compliance with policies, rules and standards for information security"},
	{ID: "A.5.37", Theme: "organizational", Title: "Documented operating procedures"},
	// People (8)
	{ID: "A.6.1", Theme: "people", Title: "Screening"},
	{ID: "A.6.2", Theme: "people", Title: "Terms and conditions of employment"},
	{ID: "A.6.3", Theme: "people", Title: "Information security awareness, education and training"},
	{ID: "A.6.4", Theme: "people", Title: "Disciplinary process"},
	{ID: "A.6.5", Theme: "people", Title: "Responsibilities after termination or change of employment"},
	{ID: "A.6.6", Theme: "people", Title: "Confidentiality or non-disclosure agreements"},
	{ID: "A.6.7", Theme: "people", Title: "Remote working"},
	{ID: "A.6.8", Theme: "people", Title: "Information security event reporting"},
	// Physical (14)
	{ID: "A.7.1", Theme: "physical", Title: "Physical security perimeters"},
	{ID: "A.7.2", Theme: "physical", Title: "Physical entry"},
	{ID: "A.7.3", Theme: "physical", Title: "Securing offices, rooms and facilities"},
	{ID: "A.7.4", Theme: "physical", Title: "Physical security monitoring"},
	{ID: "A.7.5", Theme: "physical", Title: "Protecting against physical and environmental threats"},
	{ID: "A.7.6", Theme: "physical", Title: "Working in secure areas"},
	{ID: "A.7.7", Theme: "physical", Title: "Clear desk and clear screen"},
	{ID: "A.7.8", Theme: "physical", Title: "Equipment siting and protection"},
	{ID: "A.7.9", Theme: "physical", Title: "Security of assets off-premises"},
	{ID: "A.7.10", Theme: "physical", Title: "Storage media"},
	{ID: "A.7.11", Theme: "physical", Title: "Supporting utilities"},
	{ID: "A.7.12", Theme: "physical", Title: "Cabling security"},
	{ID: "A.7.13", Theme: "physical", Title: "Equipment maintenance"},
	{ID: "A.7.14", Theme: "physical", Title: "Secure disposal or re-use of equipment"},
	// Technological (34)
	{ID: "A.8.1", Theme: "technological", Title: "User endpoint devices"},
	{ID: "A.8.2", Theme: "technological", Title: "Privileged access rights"},
	{ID: "A.8.3", Theme: "technological", Title: "Information access restriction"},
	{ID: "A.8.4", Theme: "technological", Title: "Access to source code"},
	{ID: "A.8.5", Theme: "technological", Title: "Secure authentication"},
	{ID: "A.8.6", Theme: "technological", Title: "Capacity management"},
	{ID: "A.8.7", Theme: "technological", Title: "Protection against malware"},
	{ID: "A.8.8", Theme: "technological", Title: "Management of technical vulnerabilities"},
	{ID: "A.8.9", Theme: "technological", Title: "Configuration management"},
	{ID: "A.8.10", Theme: "technological", Title: "Information deletion"},
	{ID: "A.8.11", Theme: "technological", Title: "Data masking"},
	{ID: "A.8.12", Theme: "technological", Title: "Data leakage prevention"},
	{ID: "A.8.13", Theme: "technological", Title: "Information backup"},
	{ID: "A.8.14", Theme: "technological", Title: "Redundancy of information processing facilities"},
	{ID: "A.8.15", Theme: "technological", Title: "Logging"},
	{ID: "A.8.16", Theme: "technological", Title: "Monitoring activities"},
	{ID: "A.8.17", Theme: "technological", Title: "Clock synchronization"},
	{ID: "A.8.18", Theme: "technological", Title: "Use of privileged utility programs"},
	{ID: "A.8.19", Theme: "technological", Title: "Installation of software on operational systems"},
	{ID: "A.8.20", Theme: "technological", Title: "Networks security"},
	{ID: "A.8.21", Theme: "technological", Title: "Security of network services"},
	{ID: "A.8.22", Theme: "technological", Title: "Segregation of networks"},
	{ID: "A.8.23", Theme: "technological", Title: "Web filtering"},
	{ID: "A.8.24", Theme: "technological", Title: "Use of cryptography"},
	{ID: "A.8.25", Theme: "technological", Title: "Secure development life cycle"},
	{ID: "A.8.26", Theme: "technological", Title: "Application security requirements"},
	{ID: "A.8.27", Theme: "technological", Title: "Secure system architecture and engineering principles"},
	{ID: "A.8.28", Theme: "technological", Title: "Secure coding"},
	{ID: "A.8.29", Theme: "technological", Title: "Security testing in development and acceptance"},
	{ID: "A.8.30", Theme: "technological", Title: "Outsourced development"},
	{ID: "A.8.31", Theme: "technological", Title: "Separation of development, test and production environments"},
	{ID: "A.8.32", Theme: "technological", Title: "Change management"},
	{ID: "A.8.33", Theme: "technological", Title: "Test information"},
	{ID: "A.8.34", Theme: "technological", Title: "Protection of information systems during audit testing"},
}
